"""Printable HTML exports for the Health Assessment module."""
from __future__ import annotations

import html
from typing import Optional

from app.services.assessment_service import (
    default_source,
    get_assessment_checklists,
    get_head_to_toe_sequence,
    get_red_flags,
    get_vital_signs,
)

_PRINT_STYLES = """
  body { font-family: Georgia, serif; margin: 2cm; color: #111; }
  h1 { color: #0f172a; border-bottom: 2px solid #a78bfa; padding-bottom: 8px; }
  h2 { color: #5b21b6; font-size: 14px; margin-top: 28px; border-bottom: 1px solid #ddd6fe; padding-bottom: 4px; }
  h3 { color: #4c1d95; font-size: 12px; margin-top: 18px; }
  .meta { color: #666; font-size: 12px; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; margin-bottom: 16px; }
  th { background: #4c1d95; color: white; padding: 8px; text-align: left; }
  td { padding: 6px 8px; border-bottom: 1px solid #ddd; vertical-align: top; }
  tr:nth-child(even) { background: #faf5ff; }
  .rationale { color: #475569; font-size: 10px; font-style: italic; }
  .step-num { font-weight: 700; color: #7c3aed; }
  .callout { background: #faf5ff; border-left: 3px solid #a78bfa; padding: 12px 16px; margin: 16px 0; font-size: 11px; }
  .card-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 16px 0; }
  .rf-card {
    border: 1px solid #c4b5fd; border-radius: 6px; padding: 10px 12px;
    page-break-inside: avoid; background: #fefefe;
  }
  .rf-card.immediate { border-left: 4px solid #dc2626; }
  .rf-card.urgent { border-left: 4px solid #f59e0b; }
  .rf-finding { font-weight: 700; font-size: 11px; margin-bottom: 6px; }
  .rf-action { font-size: 10px; color: #334155; }
  .rf-meta { font-size: 9px; color: #64748b; margin-top: 6px; text-transform: uppercase; letter-spacing: 0.04em; }
  .checklist { margin-bottom: 24px; page-break-inside: avoid; }
  .checklist-desc { color: #64748b; font-size: 10px; margin-bottom: 8px; }
  .check-item { padding: 4px 0; font-size: 11px; border-bottom: 1px dotted #e2e8f0; }
  .check-box { display: inline-block; width: 12px; height: 12px; border: 1px solid #94a3b8; margin-right: 8px; vertical-align: middle; }
  .clinical-note { color: #64748b; font-size: 9px; margin-left: 22px; }
  @media print {
    body { margin: 1cm; }
    .card-grid { grid-template-columns: 1fr 1fr; }
  }
"""


def _esc(text: Optional[str]) -> str:
    return html.escape(str(text or ""), quote=True)


def _wrap_document(title: str, body: str, meta: str) -> str:
    return f"""<!DOCTYPE html>
<html><head>
<meta charset="UTF-8">
<title>The Ward — {title}</title>
<style>{_PRINT_STYLES}</style>
</head><body>
<h1>The Ward — Health Assessment</h1>
<p class="meta">{meta}</p>
{body}
<p class="meta">Generated by The Ward — local-first nursing study suite</p>
</body></html>"""


def build_head_to_toe_sheet_html(title: str = "Head-to-Toe Sequence Sheet") -> str:
    """Printable head-to-toe assessment sequence with vital sign norms."""
    src = default_source()
    steps = get_head_to_toe_sequence()
    vitals = get_vital_signs()

    step_rows = ""
    for step in steps:
        step_rows += f"""
        <tr>
            <td class="step-num">{step.get('order', '')}</td>
            <td><strong>{_esc(step.get('step', ''))}</strong><br>{_esc(step.get('description', ''))}</td>
            <td class="rationale">{_esc(step.get('rationale', ''))}</td>
        </tr>"""

    vital_rows = ""
    for norm in vitals.get("norms", []):
        vital_rows += f"""
        <tr>
            <td><strong>{_esc(norm.get('parameter', ''))}</strong></td>
            <td>{_esc(norm.get('normal', ''))}</td>
            <td class="rationale">{_esc(norm.get('notes', ''))}</td>
        </tr>"""

    body = f"""
<div class="callout">
  <strong>Clinical tip:</strong> Follow this systematic order for a complete exam.
  When you identify a red flag, stop routine sequencing and escalate immediately.
</div>

<h2>Assessment Sequence ({len(steps)} steps)</h2>
<table>
  <thead><tr><th>#</th><th>Step &amp; Technique</th><th>Rationale</th></tr></thead>
  <tbody>{step_rows}</tbody>
</table>

<h2>{_esc(vitals.get('title', 'Vital Sign Norms'))}</h2>
<table>
  <thead><tr><th>Parameter</th><th>Normal Range</th><th>Notes</th></tr></thead>
  <tbody>{vital_rows}</tbody>
</table>"""

    meta = (
        f"{title} · {len(steps)} steps · "
        f"{len(vitals.get('norms', []))} vital parameters · "
        f"Source: {src.citation} · New River CTC ADN"
    )
    return _wrap_document(title, body, meta)


def build_red_flags_sheet_html(title: str = "Red Flag Quick Reference Cards") -> str:
    """Printable red-flag cards grouped by body system."""
    src = default_source()
    flags = get_red_flags()

    by_system: dict[str, list[dict]] = {}
    for flag in flags:
        system = flag.get("system", "general")
        by_system.setdefault(system, []).append(flag)

    sections = ""
    for system in sorted(by_system.keys()):
        cards = ""
        for flag in by_system[system]:
            priority = flag.get("priority", "urgent")
            cards += f"""
            <div class="rf-card {priority}">
                <div class="rf-finding">{_esc(flag.get('finding', ''))}</div>
                <div class="rf-action"><strong>Action:</strong> {_esc(flag.get('action', ''))}</div>
                <div class="rf-meta">{_esc(system)} · {_esc(priority)}</div>
            </div>"""
        sections += f"""
        <h2>{_esc(system.replace('_', ' ').title())}</h2>
        <div class="card-grid">{cards}</div>"""

    immediate = sum(1 for f in flags if f.get("priority") == "immediate")
    urgent = len(flags) - immediate

    body = f"""
<div class="callout">
  <strong>When you see a red flag:</strong> Stop routine assessment, intervene within scope,
  document objectively, and notify the provider. {immediate} immediate · {urgent} urgent findings.
</div>
{sections}"""

    meta = (
        f"{title} · {len(flags)} critical findings · "
        f"Source: {src.citation} · Print → cut cards for clinical prep"
    )
    return _wrap_document(title, body, meta)


def build_checklists_pack_html(title: str = "Assessment Checklists Pack") -> str:
    """Printable pack of all assessment checklists with checkbox items."""
    src = default_source()
    checklists = get_assessment_checklists()

    sections = ""
    total_items = 0
    for checklist in checklists:
        items_html = ""
        for item in checklist.get("items", []):
            total_items += 1
            note = item.get("clinical_note", "")
            note_html = (
                f'<div class="clinical-note">{_esc(note)}</div>' if note else ""
            )
            items_html += f"""
            <div class="check-item">
                <span class="check-box"></span>{_esc(item.get('text', ''))}
                {note_html}
            </div>"""

        sections += f"""
        <div class="checklist">
            <h2>{_esc(checklist.get('title', ''))}</h2>
            <p class="checklist-desc">{_esc(checklist.get('description', ''))}</p>
            {items_html}
        </div>"""

    body = f"""
<div class="callout">
  Check off items during clinical, simulation, or skills lab.
  {len(checklists)} checklists · {total_items} total items.
</div>
{sections}"""

    meta = (
        f"{title} · {len(checklists)} checklists · {total_items} items · "
        f"Source: {src.citation} · New River CTC ADN"
    )
    return _wrap_document(title, body, meta)