"""Build dosage.json and dosage_drug_classes.json."""
from __future__ import annotations

from typing import Any

from scripts.restore_content_payload.common import mcq, src


def build_drug_classes() -> dict[str, Any]:
    s = src("dosage")

    def dc(
        did: str, name: str, category: str, moa: str, implications: list[str],
        monitoring: list[str], side_effects: list[str], contraindications: list[str],
        interactions: list[str], prototypes: list[str],
    ) -> dict[str, Any]:
        return {
            "id": did, "name": name, "category": category, "category_label": category,
            "mechanism_of_action": moa, "prototype_drugs": prototypes,
            "nursing_implications": implications, "monitoring": monitoring,
            "common_side_effects": side_effects, "contraindications": contraindications,
            "interactions": interactions,
            "clinical_why": implications[0] if implications else "",
            "source": s,
        }

    classes = [
        dc("acetaminophen", "Acetaminophen", "Analgesic/Antipyretic",
           "Central inhibition of prostaglandin synthesis — minimal peripheral anti-inflammatory effect",
           ["Max 4 g/day adults; check combination products", "Hepatotoxicity risk — assess alcohol use", "NAC antidote for overdose"],
           ["Liver enzymes with chronic use", "Pain and fever response"],
           ["Hepatotoxicity at overdose", "Rash (rare)"],
           ["Severe hepatic impairment"],
           ["Warfarin may increase INR with chronic high doses"],
           ["Tylenol", "acetaminophen"]),
        dc("anticoagulants", "Anticoagulants", "Anticoagulant",
           "Inhibit clotting cascade — warfarin (vitamin K antagonist); heparin/LMWH (antithrombin activation); DOACs target factor Xa or thrombin",
           ["ISMP high-alert — independent double-check", "Bleeding precautions; fall risk", "Never IM injections with heparin"],
           ["INR for warfarin", "aPTT/anti-Xa per protocol", "Signs of bleeding", "Platelets for heparin-induced thrombocytopenia"],
           ["Bleeding", "HIT with heparin", "Bruising"],
           ["Active bleeding", "HIT with heparin"],
           ["NSAIDs increase bleeding", "Many drug interactions with warfarin"],
           ["warfarin", "heparin", "enoxaparin", "apixaban"]),
        dc("insulin", "Insulin", "Antidiabetic",
           "Allows glucose uptake into cells — lowers blood glucose",
           ["ISMP high-alert double-check", "Only regular insulin IV", "Rotate injection sites", "Hypoglycemia protocol: 15 g fast carb, recheck 15 min"],
           ["Blood glucose before meals and HS", "Onset/peak/duration by type", "Signs of hypoglycemia"],
           ["Hypoglycemia", "Lipohypertrophy at sites", "Weight gain"],
           ["Hypoglycemia unawareness without monitoring plan"],
           ["Beta-blockers mask tachycardia of hypoglycemia"],
           ["regular", "NPH", "glargine", "lispro"]),
        dc("opioid-analgesics", "Opioid Analgesics", "Analgesic",
           "Agonize mu receptors — decrease pain perception; respiratory depression",
           ["Assess respiratory rate before each dose", "Naloxone available for overdose", "Bowel regimen for constipation prophylaxis"],
           ["RR, sedation, pain score", "Bowel function", "CNS depression"],
           ["Respiratory depression", "Constipation", "Sedation", "Nausea"],
           ["MAOI within 14 days", "Severe respiratory depression"],
           ["CNS depressants potentiate sedation", "MAOIs — serotonin syndrome risk"],
           ["morphine", "fentanyl", "oxycodone", "hydromorphone"]),
        dc("beta-blockers", "Beta-Blockers", "Antihypertensive/Antiarrhythmic",
           "Block beta-adrenergic receptors — decrease HR and contractility",
           ["Never stop abruptly — rebound angina/HTN", "Mask hypoglycemia symptoms", "Hold if HR <60 or SBP low per order"],
           ["HR and BP", "Bronchospasm in asthmatics", "Fatigue"],
           ["Bradycardia", "Hypotension", "Bronchospasm", "Fatigue"],
           ["Asthma/COPD severe bronchospasm", "Heart block", "Decompensated HF"],
           ["Calcium channel blockers — additive bradycardia"],
           ["metoprolol", "atenolol", "propranolol"]),
        dc("ace-inhibitors", "ACE Inhibitors", "Antihypertensive",
           "Block conversion of angiotensin I to II — vasodilation, reduced aldosterone",
           ["First-dose hypotension — rise slowly", "Monitor potassium and creatinine", "Angioedema is emergency"],
           ["BP", "K+", "creatinine", "Dry cough"],
           ["Dry cough", "Hyperkalemia", "Angioedema", "Hypotension"],
           ["Pregnancy", "Angioedema history", "Bilateral renal artery stenosis"],
           ["Potassium supplements/NSAIDs increase K+"],
           ["lisinopril", "enalapril", "ramipril"]),
        dc("diuretics", "Diuretics", "Diuretic",
           "Increase renal excretion of fluid/electrolytes — loops, thiazides, K+-sparing",
           ["Monitor daily weights and I&O", "Assess orthostatic vitals", "Give morning diuretics to avoid nocturia"],
           ["K+", "Na+", "Mg2+", "BUN/creatinine", "Daily weights"],
           ["Hypokalemia", "Hypotension", "Dehydration", "Ototoxicity (loops)"],
           ["Anuria", "Severe electrolyte depletion"],
           ["NSAIDs reduce diuretic effect", "Digoxin toxicity with hypokalemia"],
           ["furosemide", "hydrochlorothiazide", "spironolactone"]),
        dc("fluoroquinolones", "Fluoroquinolones", "Antibiotic",
           "Inhibit DNA gyrase — bactericidal broad spectrum",
           ["Black box: tendinitis/tendon rupture", "Avoid in children unless no alternative", "QT prolongation risk"],
           ["Tendon pain", "QTc if risk factors", "C. diff diarrhea"],
           ["Tendon rupture", "QT prolongation", "CNS effects", "C. diff"],
           ["Myasthenia gravis", "History of tendon rupture with quinolone"],
           ["Antacids reduce absorption", "QT drugs increase arrhythmia risk"],
           ["ciprofloxacin", "levofloxacin", "moxifloxacin"]),
        dc("aminoglycosides", "Aminoglycosides", "Antibiotic",
           "Inhibit bacterial protein synthesis — concentration-dependent killing",
           ["Narrow therapeutic index — peak/trough levels", "Nephrotoxicity and ototoxicity monitoring", "Once-daily dosing per protocol"],
           ["Peak/trough levels", "Creatinine", "Hearing changes"],
           ["Nephrotoxicity", "Ototoxicity", "Neuromuscular blockade"],
           ["Renal failure without dose adjustment"],
           ["Loop diuretics increase ototoxicity"],
           ["gentamicin", "tobramycin", "amikacin"]),
        dc("proton-pump-inhibitors", "Proton Pump Inhibitors", "GI",
           "Irreversibly inhibit gastric H+/K+ ATPase — reduce acid secretion",
           ["Give before meals for best effect", "Long-term use: B12, Mg, fracture risk", "Do not crush delayed-release"],
           ["GI bleeding response", "Magnesium with chronic use"],
           ["Headache", "Diarrhea", "C. diff risk with prolonged use"],
           ["Hypersensitivity"],
           ["Clopidogrel interaction with omeprazole (variable significance)"],
           ["omeprazole", "pantoprazole", "esomeprazole"]),
        dc("benzodiazepines", "Benzodiazepines", "Sedative/Anxiolytic",
           "Enhance GABA-A receptor activity — CNS depression",
           ["Fall risk in older adults — Beers Criteria", "Avoid abrupt discontinuation — seizure risk", "Reverse with flumazenil only per protocol (seizure risk)"],
           ["Sedation", "Respiratory rate", "Fall risk"],
           ["Sedation", "Confusion", "Dependence", "Respiratory depression with opioids"],
           ["Acute narrow-angle glaucoma", "Severe respiratory depression"],
           ["Opioids — fatal respiratory depression", "CNS depressants additive"],
           ["lorazepam", "diazepam", "midazolam"]),
        dc("antipsychotics", "Antipsychotics", "Psychotropic",
           "Block dopamine D2 receptors (typical) and multiple receptors (atypical)",
           ["Monitor for extrapyramidal symptoms", "Metabolic monitoring with atypicals", "Neuroleptic malignant syndrome rare emergency"],
           ["Weight, glucose, lipids", "EPS", "QTc"],
           ["EPS", "Weight gain", "Sedation", "Orthostatic hypotension"],
           ["NMS history"],
           ["QT-prolonging drugs", "CNS depressants"],
           ["haloperidol", "risperidone", "olanzapine", "quetiapine"]),
        dc("ssri-antidepressants", "SSRIs", "Antidepressant",
           "Selective serotonin reuptake inhibition — increases synaptic serotonin",
           ["Suicide assessment especially young adults at initiation", "Serotonin syndrome with MAOIs/linezolid", "Do not stop abruptly"],
           ["Mood", "Suicidal ideation", "GI tolerance"],
           ["Nausea", "Sexual dysfunction", "Insomnia", "Serotonin syndrome"],
           ["MAOI within 14 days"],
           ["MAOIs", "Triptans", "Linezolid — serotonin syndrome"],
           ["sertraline", "fluoxetine", "escitalopram"]),
        dc("lithium", "Lithium", "Mood stabilizer",
           "Alters sodium transport and neurotransmission — narrow therapeutic index",
           ["Maintain consistent sodium and fluid intake", "Therapeutic level 0.6–1.2 mEq/L typically", "Toxicity: coarse tremor, confusion, ataxia"],
           ["Lithium levels", "Renal function", "Thyroid"],
           ["Polyuria", "Tremor", "Weight gain", "Toxicity"],
           ["Severe renal impairment", "Dehydration"],
           ["NSAIDs and diuretics increase levels"],
           ["lithium carbonate"]),
        dc("digoxin", "Digoxin", "Cardiac glycoside",
           "Inhibits Na+/K+ ATPase — increases contractility; slows AV conduction",
           ["Hold for HR <60 or PR prolongation per order", "Hypokalemia increases toxicity risk", "Assess apical pulse 1 full minute before oral dose"],
           ["HR", "K+", "digoxin level", "Visual changes (yellow-green halos)"],
           ["Nausea", "Bradycardia", "Arrhythmias", "Visual disturbances"],
           ["Ventricular fibrillation", "Heart block", "Digoxin toxicity"],
           ["Amiodarone increases levels", "Hypokalemia increases toxicity"],
           ["digoxin"]),
        dc("nitroglycerin", "Nitrates", "Anti-anginal",
           "Nitric oxide donor — venodilation reduces preload",
           ["Store in dark glass; replace opened bottle per policy", "SBP must be >90 for NTG", "PDE-5 inhibitors contraindicated 24–48 hr"],
           ["BP", "Headache", "Chest pain relief"],
           ["Headache", "Hypotension", "Reflex tachycardia"],
           ["SBP <90", "PDE-5 inhibitor use", "Severe anemia"],
           ["PDE-5 inhibitors — severe hypotension"],
           ["nitroglycerin", "isosorbide"]),
        dc("antihistamines", "Antihistamines (1st gen)", "Allergy",
           "Block H1 receptors — sedation and anticholinergic effects",
           ["Sedation and fall risk in older adults", "Anticholinergic: dry mouth, urinary retention", "Avoid driving"],
           ["Sedation", "Urinary retention in BPH"],
           ["Sedation", "Dry mouth", "Urinary retention", "Confusion in elderly"],
           ["Narrow-angle glaucoma", "BPH with retention"],
           ["CNS depressants additive"],
           ["diphenhydramine", "hydroxyzine"]),
        dc("bronchodilators", "Bronchodilators", "Respiratory",
           "Beta-2 agonists relax bronchial smooth muscle; anticholinergics block muscarinic receptors",
           ["Albuterol first-line rescue", "Tremor and tachycardia common", "Teach inhaler technique"],
           ["RR", "SpO2", "Peak flow if ordered"],
           ["Tremor", "Tachycardia", "Hypokalemia with high doses"],
           ["Tachyarrhythmia uncontrolled"],
           ["Beta-blockers may blunt beta-2 effect (cardioselective safer)"],
           ["albuterol", "ipratropium", "salmeterol"]),
    ]
    pharm_categories = [
        {"id": "analgesics", "label": "Analgesics & Sedatives", "class_ids": ["acetaminophen", "opioid-analgesics", "benzodiazepines"]},
        {"id": "cardiovascular", "label": "Cardiovascular", "class_ids": ["anticoagulants", "beta-blockers", "ace-inhibitors", "diuretics", "digoxin", "nitroglycerin"]},
        {"id": "endocrine", "label": "Endocrine", "class_ids": ["insulin"]},
        {"id": "antiinfectives", "label": "Anti-infectives", "class_ids": ["fluoroquinolones", "aminoglycosides"]},
        {"id": "gi", "label": "Gastrointestinal", "class_ids": ["proton-pump-inhibitors"]},
        {"id": "psychotropic", "label": "Psychotropic", "class_ids": ["antipsychotics", "ssri-antidepressants", "lithium"]},
        {"id": "respiratory", "label": "Respiratory & Allergy", "class_ids": ["bronchodilators", "antihistamines"]},
    ]
    return {"drug_classes": classes, "pharm_categories": pharm_categories, "source": s}


def build_dosage() -> dict[str, Any]:
    s = src("dosage")
    calc_types = [
        {"id": "tablet_capsule", "name": "Tablet/Capsule", "formula": "Ordered ÷ Available = number of tablets", "description": "Solid oral dose calculations", "source": s},
        {"id": "liquid", "name": "Liquid Oral", "formula": "(Ordered ÷ Available) × Volume = mL", "description": "Oral suspensions and solutions", "source": s},
        {"id": "iv_drip_gtt", "name": "IV Drip (gtt/min)", "formula": "(Volume × Drop Factor) ÷ Time (min)", "description": "Manual gravity infusion rate", "source": s},
        {"id": "iv_drip_ml_hr", "name": "IV Pump (mL/hr)", "formula": "Volume ÷ Time (hours)", "description": "Electronic infusion pump programming", "source": s},
        {"id": "weight_based", "name": "Weight-Based", "formula": "Weight (kg) × Dose/kg = total mg", "description": "Pediatric and many adult high-risk meds", "source": s},
        {"id": "pediatric", "name": "Pediatric", "formula": "Same as weight-based with pediatric safety checks", "description": "Children are not small adults", "source": s},
        {"id": "geriatric", "name": "Geriatric Adjustment", "formula": "Adult dose × 0.5–0.75 start low", "description": "Start low, go slow — Beers Criteria review", "source": s},
    ]
    first_principles = {
        "tablet_capsule": {"steps": ["Desired (ordered dose)", "Have (dose per tablet)", "Divide desired by have", "Clinical check: splittable? max daily dose?"], "units": "tablets", "safety": ["High-alert double-check", "Never crush ER/enteric unless ordered"]},
        "liquid": {"steps": ["Desired dose", "Have (drug amount in volume)", "Set up ratio", "Multiply by volume to get mL"], "units": "mL", "safety": ["Use oral syringe", "Shake suspensions"]},
        "iv_drip_gtt": {"steps": ["Volume to infuse", "Drop factor from tubing", "Time in minutes", "Multiply V×DF, divide by minutes"], "units": "gtt/min", "safety": ["Count drops 1 minute", "Recheck frequently"]},
        "iv_drip_ml_hr": {"steps": ["Volume", "Convert time to hours", "Divide volume by hours"], "units": "mL/hr", "safety": ["Pump double-check for high-alert"]},
        "weight_based": {"steps": ["Weight in kg", "Dose per kg from order", "Multiply", "Compare to max dose"], "units": "mg", "safety": ["Weigh patient when possible"]},
        "pediatric": {"steps": ["Confirm kg weight", "Calculate mg", "Verify pediatric reference"], "units": "mg", "safety": ["Pharmacist consult for neonates"]},
        "geriatric": {"steps": ["Standard adult dose", "Apply reduction factor", "Titrate"], "units": "mg", "safety": ["Renal/hepatic adjustment may be needed"]},
    }
    error_traps = [
        {"id": "trap-units", "title": "Unit Conversion Errors", "trap": "Confusing mg, mcg, g, and units", "fix": "Convert to one system before calculating; mcg ≠ mg (1000× difference).", "example": "Ordered 0.5 mg but label in mcg — 500 mcg", "source": s},
        {"id": "trap-decimal", "title": "Decimal Point Errors", "trap": "Misplaced decimal — tenfold overdose", "fix": "Leading zero for doses <1 (0.5 mg not .5 mg); no trailing zero on whole numbers.", "example": "2.0 mg misread as 20 mg", "source": s},
        {"id": "trap-division", "title": "Inverted Division", "trap": "Dividing available by ordered instead of ordered by available", "fix": "Desired ÷ Have — ask 'how many units to get desired dose?'", "example": "Ordered 500 mg, tablet 250 mg → 2 tablets not 0.5", "source": s},
        {"id": "trap-time", "title": "Time Unit Errors", "trap": "Using minutes when formula needs hours for mL/hr", "fix": "Always convert minutes to hours for pump rates.", "example": "1000 mL over 8 hr = 125 mL/hr not 1000÷8 min", "source": s},
        {"id": "trap-drop", "title": "Wrong Drop Factor", "trap": "Assuming 15 gtt/mL when tubing is 10 or 60", "fix": "Read drop factor on IV tubing package every time.", "example": "Microdrip always 60 gtt/mL", "source": s},
        {"id": "trap-weight", "title": "Weight in Pounds", "trap": "Using lbs instead of kg in weight-based calc", "fix": "kg = lbs ÷ 2.2 before multiplying dose/kg.", "example": "44 lbs = 20 kg not 44 kg", "source": s},
        {"id": "trap-rounding", "title": "Premature Rounding", "trap": "Rounding intermediate steps causes error", "fix": "Round only at final step per policy.", "example": "0.333 × 3 = 0.999 → clinical judgment on 1 mL", "source": s},
        {"id": "trap-concentration", "title": "Reconstitution Concentration", "trap": "Using vial total volume instead of final concentration", "fix": "Read label after reconstitution — mg per mL.", "example": "1 g in 10 mL = 100 mg/mL", "source": s},
    ]
    pharmacology_safety = [
        {"id": "therapeutic_range", "title": "Therapeutic Range", "concept": "Drug plasma concentration window between subtherapeutic and toxic", "nursing_action": "Link calculations to expected response and toxicity monitoring.", "clinical_why": "Digoxin, lithium, aminoglycosides have narrow indices.", "source": s},
        {"id": "high_alert", "title": "High-Alert Medications", "concept": "ISMP list — insulin, anticoagulants, opioids, chemo, concentrated electrolytes", "nursing_action": "Independent double-check per facility policy.", "clinical_why": "Highest harm potential if miscalculated.", "source": s},
        {"id": "five_rights", "title": "Five Rights", "concept": "Right patient, drug, dose, route, time", "nursing_action": "Verify against MAR/eMAR and patient identifiers.", "clinical_why": "Calculation correct but wrong patient still causes harm.", "source": s},
        {"id": "look_alike", "title": "Look-Alike Sound-Alike (LASA)", "concept": "Similar names/packaging increase error risk", "nursing_action": "Tall-man lettering; separate storage; read label 3 times.", "clinical_why": "hydroxyzine vs hydralazine type errors.", "source": s},
        {"id": "renal_hepatic", "title": "Renal/Hepatic Dose Adjustment", "concept": "Impaired elimination increases toxicity risk", "nursing_action": "Hold and clarify if dose seems standard but CrCl low.", "clinical_why": "Many drugs require renal dose adjustment.", "source": s},
        {"id": "pediatric_safety", "title": "Pediatric Dosing Safety", "concept": "Weight-based with maximum dose caps", "nursing_action": "Never exceed adult max even if mg/kg calculation higher.", "clinical_why": "Overdose is leading pediatric medication error.", "source": s},
    ]
    practice_problems = [
        {"id": "dos-p01", "calc_type": "tablet_capsule", "question": "Order: Digoxin 0.25 mg PO daily. Available: 0.125 mg tablets. How many tablets?", "options": ["0.5 tablet", "1 tablet", "2 tablets", "2.5 tablets"], "correct_index": 2, "answer": "2 tablets", "explanation": "0.25 ÷ 0.125 = 2 tablets.", "trap": "Dividing 0.125 ÷ 0.25 gives wrong answer.", "nursing_note": "Assess apical pulse 1 full minute before giving.", "source": s},
        {"id": "dos-p02", "calc_type": "liquid", "question": "Order: Acetaminophen 650 mg PO. Available: 325 mg/5 mL. How many mL?", "options": ["5 mL", "10 mL", "15 mL", "20 mL"], "correct_index": 1, "answer": "10 mL", "explanation": "(650 ÷ 325) × 5 = 10 mL.", "trap": "Forgetting to multiply by volume.", "nursing_note": "Max 4 g/day from all sources.", "source": s},
        {"id": "dos-p03", "calc_type": "iv_drip_gtt", "question": "Infuse 1000 mL over 8 hr using 15 gtt/mL tubing. gtt/min?", "options": ["21 gtt/min", "31 gtt/min", "42 gtt/min", "62 gtt/min"], "correct_index": 1, "answer": "31 gtt/min", "explanation": "(1000 × 15) ÷ 480 min = 31.25 ≈ 31 gtt/min.", "trap": "Using 8 instead of 480 minutes.", "nursing_note": "Count drops full minute at bedside.", "source": s},
        {"id": "dos-p04", "calc_type": "iv_drip_ml_hr", "question": "1000 mL NS over 10 hours. Pump rate mL/hr?", "options": ["50 mL/hr", "100 mL/hr", "125 mL/hr", "250 mL/hr"], "correct_index": 1, "answer": "100 mL/hr", "explanation": "1000 ÷ 10 = 100 mL/hr.", "trap": "Dividing by minutes.", "nursing_note": "Document pump settings.", "source": s},
        {"id": "dos-p05", "calc_type": "weight_based", "question": "Order: 5 mg/kg for 44 lb child. Dose in mg? (44 lb = 20 kg)", "options": ["44 mg", "100 mg", "220 mg", "440 mg"], "correct_index": 1, "answer": "100 mg", "explanation": "20 kg × 5 mg/kg = 100 mg.", "trap": "Using 44 kg instead of 20 kg.", "nursing_note": "Verify against max single dose.", "source": s},
        {"id": "dos-p06", "calc_type": "liquid", "question": "Order: 0.5 mg. Available: 2 mg/mL. How many mL?", "options": ["0.1 mL", "0.25 mL", "0.5 mL", "1 mL"], "correct_index": 1, "answer": "0.25 mL", "explanation": "0.5 ÷ 2 = 0.25 mL — use calibrated syringe.", "trap": "Decimal placement.", "nursing_note": "Small volumes need insulin/oral syringe.", "source": s},
        {"id": "dos-p07", "calc_type": "tablet_capsule", "question": "Order: 1500 mg acetaminophen. Available: 500 mg tablets. Tablets?", "options": ["1", "2", "3", "4"], "correct_index": 2, "answer": "3 tablets", "explanation": "1500 ÷ 500 = 3.", "trap": "Exceeding 4 g/day from multiple nurses.", "nursing_note": "Check all acetaminophen sources.", "source": s},
        {"id": "dos-p08", "calc_type": "iv_drip_gtt", "question": "50 mL antibiotic over 30 min, microdrip (60 gtt/mL). gtt/min?", "options": ["50", "100", "150", "200"], "correct_index": 1, "answer": "100 gtt/min", "explanation": "(50 × 60) ÷ 30 = 100 gtt/min.", "trap": "Using 15 gtt/mL factor.", "nursing_note": "Microdrip = 60 gtt/mL always.", "source": s},
        {"id": "dos-p09", "calc_type": "weight_based", "question": "Heparin 18 units/kg bolus for 70 kg patient. Bolus units?", "options": ["560", "1260", "1800", "2520"], "correct_index": 1, "answer": "1260 units", "explanation": "70 × 18 = 1260 units.", "trap": "High-alert — double-check.", "nursing_note": "ISMP high-alert medication.", "source": s},
        {"id": "dos-p10", "calc_type": "geriatric", "question": "Standard dose 10 mg; start at 75% for older adult. Starting dose?", "options": ["2.5 mg", "5 mg", "7.5 mg", "10 mg"], "correct_index": 2, "answer": "7.5 mg", "explanation": "10 × 0.75 = 7.5 mg.", "trap": "Full adult dose in frail elderly.", "nursing_note": "Titrate slowly; fall precautions.", "source": s},
        {"id": "dos-p11", "calc_type": "liquid", "question": "Order: 400 mg. Available: 100 mg/5 mL. mL?", "options": ["5 mL", "10 mL", "20 mL", "40 mL"], "correct_index": 2, "answer": "20 mL", "explanation": "(400÷100)×5 = 20 mL.", "trap": "Unit mismatch.", "nursing_note": "Stay with patient until swallowed.", "source": s},
        {"id": "dos-p12", "calc_type": "iv_drip_ml_hr", "question": "250 mL over 2 hours. mL/hr?", "options": ["62.5", "100", "125", "250"], "correct_index": 2, "answer": "125 mL/hr", "explanation": "250 ÷ 2 = 125 mL/hr.", "trap": "Using 2 minutes.", "nursing_note": "Assess IV site during infusion.", "source": s},
        {"id": "dos-p13", "calc_type": "tablet_capsule", "question": "Order: 7.5 mg. Available: 2.5 mg tablets.", "options": ["1", "2", "3", "4"], "correct_index": 2, "answer": "3 tablets", "explanation": "7.5 ÷ 2.5 = 3.", "trap": "Rounding to 2 tablets underdoses.", "nursing_note": "Document partial doses clearly.", "source": s},
        {"id": "dos-p14", "calc_type": "weight_based", "question": "Amoxicillin 25 mg/kg/day in 2 doses for 16 kg toddler. mg per dose?", "options": ["100 mg", "200 mg", "400 mg", "800 mg"], "correct_index": 1, "answer": "200 mg", "explanation": "16×25=400 mg/day ÷ 2 = 200 mg/dose.", "trap": "Giving full daily dose once.", "nursing_note": "Liquid formulation preferred.", "source": s},
        {"id": "dos-p15", "calc_type": "iv_drip_gtt", "question": "500 mL over 4 hr, 20 gtt/mL. gtt/min?", "options": ["21", "42", "63", "84"], "correct_index": 1, "answer": "42 gtt/min", "explanation": "(500×20)÷240 = 41.67 ≈ 42.", "trap": "4 hr as 4 minutes.", "nursing_note": "Reassess rate with patient movement.", "source": s},
    ]
    drug_payload = build_drug_classes()
    return {
        "module_id": "dosage",
        "title": "NURS 145 — Drug & Dosage Calculations",
        "calc_types": calc_types,
        "first_principles": first_principles,
        "error_traps": error_traps,
        "pharmacology_safety": pharmacology_safety,
        "practice_problems": practice_problems,
        "drug_classes": drug_payload["drug_classes"],
        "pharm_categories": drug_payload["pharm_categories"],
        "source": s,
    }