"""Build pathophysiology.json."""
from __future__ import annotations

from typing import Any

from scripts.restore_content_payload.common import mcq, src


def build() -> dict[str, Any]:
    s = src("pathophysiology")
    core_concepts = [
        {"id": "homeostasis", "title": "Homeostasis & Feedback", "summary": "Dynamic equilibrium maintained by negative feedback loops", "content": "The body regulates temperature, glucose, fluid, and pH through sensors, control centers, and effectors. Disease begins when feedback fails or set points shift.", "clinical_relevance": "Nursing supports compensatory mechanisms until treatment restores balance.", "nursing_implications": ["Monitor trends not single values", "Anticipate decompensation when compensation exhausts"], "source_ref": "pathophysiology"},
        {"id": "inflammation-stages", "title": "Inflammation & Immune Response", "summary": "Vascular and cellular phases — cardinal signs", "content": "Inflammation is protective response to injury/infection. Sepsis-3 defines sepsis as infection with organ dysfunction — not SIRS alone.", "clinical_relevance": "Fever, tachycardia, and hypotension may signal sepsis — hour-1 bundle.", "nursing_implications": ["Lactate and cultures per protocol", "Monitor urine output and mentation"], "source_ref": "pathophysiology"},
        {"id": "fluid-balance", "title": "Fluid & Electrolyte Balance", "summary": "Intravascular vs interstitial vs intracellular compartments", "content": "Starling forces and RAAS regulate volume. Third-spacing in burns, sepsis, and pancreatitis reduces effective circulating volume.", "clinical_relevance": "Daily weights and I&O detect fluid shifts before hypotension.", "nursing_implications": ["Assess edema, lung sounds, JVD", "Match fluid type to deficit type"], "source_ref": "pathophysiology"},
        {"id": "electrolyte-balance", "title": "Electrolyte Balance", "summary": "Na⁺, K⁺, Ca²⁺ roles in nerve, muscle, and cardiac function", "content": "Hypokalemia increases digoxin toxicity risk. Hyperkalemia causes peaked T waves progressing to sine wave — never IV K⁺ push.", "clinical_relevance": "ECG changes precede cardiac arrest in severe K⁺ abnormalities.", "nursing_implications": ["Continuous cardiac monitoring for K⁺ >6.0", "Replace K⁺ orally/IV drip per order only"], "source_ref": "pathophysiology"},
        {"id": "acid-base-abg", "title": "Acid-Base & ABG Interpretation", "summary": "pH, PaCO₂, HCO₃⁻ — respiratory vs metabolic disorders", "content": "Interpret: pH → primary disorder (PaCO₂ vs HCO₃⁻) → compensation → anion gap if metabolic acidosis (MUDPILES). COPD may have compensated chronic respiratory acidosis baseline.", "clinical_relevance": "Kussmaul respirations in metabolic acidosis; COPD retain CO₂ — titrate O₂.", "nursing_implications": ["ABG sample handling", "Report acute changes in mental status with ABG shifts"], "source_ref": "pathophysiology"},
        {"id": "compensation-decompensation", "title": "Compensation & Decompensation", "summary": "RAAS, SNS, and respiratory compensation maintain perfusion until failure", "content": "Heart failure compensation: RAAS activation, vasoconstriction, fluid retention — eventually pulmonary edema. Septic shock: warm phase then cold shock with decompensation.", "clinical_relevance": "Daily weights in CHF; lactate in sepsis.", "nursing_implications": ["Recognize when compensatory mechanisms fail", "Escalate early"], "source_ref": "pathophysiology"},
        {"id": "clotting-hemostasis", "title": "Clotting & Hemostasis", "summary": "Primary platelet plug and secondary coagulation cascade", "content": "Anticoagulants block cascade steps. HIT: thrombocytopenia with thrombosis despite low platelets — stop heparin.", "clinical_relevance": "Bleeding vs clotting risk with anticoagulation.", "nursing_implications": ["Bleeding precautions", "Monitor platelets on heparin"], "source_ref": "pathophysiology"},
        {"id": "immune-response", "title": "Innate vs Adaptive Immunity", "summary": "Neutrophils/macrophages vs lymphocytes and antibodies", "content": "Innate is immediate; adaptive provides memory (vaccines). Neutropenia requires protective precautions.", "clinical_relevance": "ANC <500 — neutropenic precautions.", "nursing_implications": ["Avoid fresh flowers/raw foods when neutropenic", "Strict hand hygiene"], "source_ref": "pathophysiology"},
        {"id": "oxygen-transport", "title": "Oxygenation & Perfusion", "summary": "O₂ delivery = CO × CaO₂; utilization at cellular level", "content": "Hypoxemia from V/Q mismatch, shunt, hypoventilation, or diffusion defect. Anemia reduces O₂ carrying capacity despite normal SpO₂.", "clinical_relevance": "SpO₂ does not replace hemoglobin assessment in hemorrhage.", "nursing_implications": ["Position for lung expansion", "Transfuse per order when indicated"], "source_ref": "pathophysiology"},
        {"id": "pain-pathway", "title": "Pain Pathophysiology", "summary": "Nociception, inflammation, and central sensitization", "content": "Acute pain warns of injury; chronic pain involves maladaptive CNS changes. Opioids modulate perception — respiratory depression is priority adverse effect.", "clinical_relevance": "Assess RR before each opioid dose.", "nursing_implications": ["Multimodal analgesia", "Non-pharmacologic measures"], "source_ref": "pathophysiology"},
    ]
    disease_processes = [
        {"id": "chf", "name": "Heart Failure", "category": "Cardiovascular", "pathophysiology": "Pump failure → RAAS activation → sodium/water retention → increased preload → pulmonary congestion (left) or systemic edema/JVD (right).", "manifestations": ["Crackles, orthopnea, S3", "Peripheral edema, JVD", "Fatigue, decreased exercise tolerance"], "nursing_priorities": ["Daily weights", "Diuretics and I&O", "High Fowler's for dyspnea", "Limit sodium/fluids per order"], "source_ref": "pathophysiology"},
        {"id": "copd", "name": "COPD", "category": "Respiratory", "pathophysiology": "Chronic inflammation and airflow limitation → air trapping → chronic hypercapnia with compensated respiratory acidosis baseline.", "manifestations": ["Barrel chest, prolonged expiration", "Chronic cough, sputum", "Hypoxemia with hypercapnia in exacerbation"], "nursing_priorities": ["SpO₂ target 88–92%", "ABG baseline monitoring", "Avoid high-flow O₂ if CO₂ retainer", "Energy conservation"], "source_ref": "pathophysiology"},
        {"id": "pneumonia", "name": "Pneumonia", "category": "Respiratory", "pathophysiology": "Alveolar consolidation impairs gas exchange → hypoxemia, fever, leukocytosis.", "manifestations": ["Crackles, dullness to percussion", "Productive cough, fever", "Tachypnea"], "nursing_priorities": ["O₂, incentive spirometry", "Antibiotics per culture", "Reposition q2h — affected-side-up only for abscess/effusion per order"], "source_ref": "pathophysiology"},
        {"id": "hypovolemic-shock", "name": "Hypovolemic Shock", "category": "Shock", "pathophysiology": "Volume loss → decreased preload → decreased CO → compensatory tachycardia then hypotension and organ hypoperfusion.", "manifestations": ["Flat neck veins early", "Tachycardia, hypotension", "Cool clammy skin, oliguria"], "nursing_priorities": ["IV access", "Fluid resuscitation per order", "Monitor urine output and lactate", "Identify source of loss"], "source_ref": "pathophysiology"},
        {"id": "cardiogenic-shock", "name": "Cardiogenic Shock", "category": "Shock", "pathophysiology": "Pump failure → decreased forward flow → pulmonary congestion and hypotension despite adequate volume.", "manifestations": ["JVD, crackles", "Hypotension, tachycardia", "Oliguria from poor forward flow"], "nursing_priorities": ["Continuous monitoring", "Inotropes per order — fluids cautiously", "Prepare for advanced support"], "source_ref": "pathophysiology"},
        {"id": "sepsis", "name": "Sepsis / Septic Shock", "category": "Shock", "pathophysiology": "Dysregulated host response to infection → vasodilation, capillary leak, microthrombi → distributive shock and organ dysfunction.", "manifestations": ["Fever or hypothermia", "Tachycardia, hypotension", "Altered mentation, oliguria"], "nursing_priorities": ["Hour-1 bundle: cultures, antibiotics, fluids, lactate", "MAP ≥65 with vasopressors if needed", "qSOFA screening"], "source_ref": "pathophysiology"},
        {"id": "dka", "name": "Diabetic Ketoacidosis", "category": "Endocrine", "pathophysiology": "Insulin deficiency → hyperglycemia, lipolysis, ketogenesis → metabolic acidosis. Total body K⁺ depleted despite serum K⁺ may be normal/high.", "manifestations": ["Polyuria, polydipsia", "Kussmaul respirations", "Fruity breath, dehydration"], "nursing_priorities": ["Fluids first", "Insulin infusion per protocol after K⁺ ≥3.3", "Never IV K⁺ push", "Monitor glucose and K⁺ hourly initially"], "source_ref": "pathophysiology"},
        {"id": "dm-type2", "name": "Type 2 Diabetes Mellitus", "category": "Endocrine", "pathophysiology": "Insulin resistance and relative insulin deficiency → chronic hyperglycemia → microvascular (retinopathy, nephropathy, neuropathy) and macrovascular complications.", "manifestations": ["Polyuria, fatigue", "Slow wound healing", "HHNS if severe hyperglycemia without ketosis"], "nursing_priorities": ["Hypoglycemia 15/15 rule", "Foot exams", "Medication adherence teaching"], "source_ref": "pathophysiology"},
        {"id": "renal-failure", "name": "Acute & Chronic Renal Failure", "category": "Renal", "pathophysiology": "Prerenal (hypoperfusion), intrarenal (ATN), postrenal (obstruction) → decreased GFR → fluid overload, hyperkalemia, metabolic acidosis, uremia.", "manifestations": ["Oliguria/anuria", "Edema, hypertension", "Hyperkalemia ECG changes"], "nursing_priorities": ["Strict I&O", "Dialysis access care", "Renal dose medications", "K⁺ restriction"], "source_ref": "pathophysiology"},
        {"id": "ards", "name": "ARDS", "category": "Respiratory", "pathophysiology": "Diffuse alveolar damage → increased permeability → non-cardiogenic pulmonary edema → refractory hypoxemia. Berlin: P/F <300 with PEEP ≥5 and bilateral infiltrates.", "manifestations": ["Severe hypoxemia", "Bilateral infiltrates", "Decreased compliance"], "nursing_priorities": ["Low tidal volume per ARDSnet", "Prone positioning if ordered", "Minimize sedation for vent synchrony"], "source_ref": "pathophysiology"},
        {"id": "stroke", "name": "Stroke (CVA)", "category": "Neurological", "pathophysiology": "Ischemic (thrombus/embolus) or hemorrhagic rupture → focal deficit by vascular territory. Penumbra is salvageable tissue in ischemic stroke.", "manifestations": ["Unilateral weakness", "Aphasia", "Sudden vision change"], "nursing_priorities": ["Last known well time", "CT before thrombolytics", "NPO until swallow eval", "HOB 30°"], "source_ref": "pathophysiology"},
        {"id": "asthma-exacerbation", "name": "Asthma Exacerbation", "category": "Respiratory", "pathophysiology": "Bronchospasm, inflammation, mucus plugging → increased airway resistance and air trapping.", "manifestations": ["Wheezes, tachypnea", "Silent chest if severe", "Hypoxemia"], "nursing_priorities": ["Bronchodilators", "O₂", "Recognize silent chest as emergency"], "source_ref": "pathophysiology"},
    ]
    compare_contrast_pairs = [
        {"id": "shock-hypo-vs-cardio", "title": "Hypovolemic vs Cardiogenic Shock", "condition_a": "Hypovolemic", "condition_b": "Cardiogenic", "key_differences": ["Flat JVD vs JVD elevated", "Dry lungs vs crackles", "Fluid bolus helps vs may worsen"], "clinical_pearls": ["Assess JVD and lung sounds before aggressive fluids", "Cardiogenic needs inotropes not large fluid bolus"], "source_ref": "pathophysiology"},
        {"id": "dka-vs-hhns", "title": "DKA vs HHNS", "condition_a": "DKA", "condition_b": "HHNS", "key_differences": ["Ketones and acidosis present in DKA", "HHNS: extreme hyperglycemia, hyperosmolarity, minimal ketones", "DKA more common type 1; HHNS type 2"], "clinical_pearls": ["Both need fluids and insulin protocol", "K⁺ replacement before insulin if low"], "source_ref": "pathophysiology"},
        {"id": "prerenal-vs-intrarenal", "title": "Prerenal vs Intrarenal AKI", "condition_a": "Prerenal", "condition_b": "Intrarenal", "key_differences": ["BUN:Cr >20:1 prerenal", "Urine Na <20 prerenal; muddy brown casts intrarenal", "Responds to fluids vs may need dialysis"], "clinical_pearls": ["Diuretics and GI bleed confound BUN:Cr", "FENa helps differentiate"], "source_ref": "pathophysiology"},
        {"id": "left-vs-right-hf", "title": "Left-Sided vs Right-Sided Heart Failure", "condition_a": "Left-sided", "condition_b": "Right-sided", "key_differences": ["Pulmonary congestion vs peripheral edema/JVD", "Orthopnea, crackles vs hepatomegaly, ascites"], "clinical_pearls": ["Both may need diuretics", "Position: high Fowler's for pulmonary edema"], "source_ref": "pathophysiology"},
        {"id": "ischemic-vs-hemorrhagic-stroke", "title": "Ischemic vs Hemorrhagic Stroke", "condition_a": "Ischemic", "condition_b": "Hemorrhagic", "key_differences": ["Thrombolytics for ischemic if within window", "Anticoagulation contraindicated in hemorrhagic", "HTN control critical in hemorrhagic"], "clinical_pearls": ["CT distinguishes type before treatment", "NPO and swallow eval for both"], "source_ref": "pathophysiology"},
    ]
    what_breaks_down_scenarios = [
        {"id": "wb-na-k-pump", "title": "Na⁺/K⁺-ATPase Failure Post-Arrest", "trigger": "Cardiac arrest with prolonged ischemia", "normal_function": "Na⁺/K⁺-ATPase maintains cellular electrochemical gradient", "breakdown": "Pump failure → intracellular Na⁺ and K⁺ leak → depolarization", "cascade": ["Peaked T waves", "Widened QRS", "Ventricular arrhythmias"], "clinical_signs": ["ECG changes", "Muscle weakness"], "nursing_response": "Continuous cardiac monitoring; K⁺ replacement per lab and protocol — never IV push", "question": "Which ECG change appears first with rising serum K⁺?", "options": ["Peaked T waves", "ST elevation", "U waves", "Prolonged PR only"], "correct_index": 0, "explanation": "Peaked T waves are early hyperkalemia sign.", "source_ref": "pathophysiology"},
        {"id": "wb-insulin-deficiency", "title": "Insulin Deficiency in DKA", "trigger": "Infection stress with missed insulin", "normal_function": "Insulin drives glucose into cells and suppresses ketogenesis", "breakdown": "Lipolysis → free fatty acids → ketone bodies → metabolic acidosis", "cascade": ["Hyperglycemia", "Osmotic diuresis", "Dehydration", "Kussmaul breathing"], "clinical_signs": ["Glucose >250", "Anion gap acidosis", "K⁺ may appear normal despite depletion"], "nursing_response": "Fluids, insulin per protocol after K⁺ ≥3.3 mEq/L", "question": "Why may serum K⁺ be normal/high in DKA despite total body depletion?", "options": ["H+/K+ shift out of cells in acidosis", "Renal retention only", "Insulin excess", "No shift occurs"], "correct_index": 0, "explanation": "Acidosis shifts K⁺ extracellularly — drops with insulin treatment.", "source_ref": "pathophysiology"},
        {"id": "wb-capillary-permeability", "title": "Capillary Leak in Septic Shock", "trigger": "Gram-negative sepsis", "normal_function": "Intact endothelium retains fluid and protein in vasculature", "breakdown": "Cytokine-mediated leak → third-spacing and relative hypovolemia", "cascade": ["Warm flushed skin early", "Hypotension despite fluids", "Oliguria", "Cold shock late"], "clinical_signs": ["Fever, tachycardia", "Hypotension", "Lactate elevation"], "nursing_response": "Early antibiotics, fluids, vasopressors for MAP ≥65", "question": "Septic shock is classified as which shock type?", "options": ["Distributive", "Hypovolemic", "Cardiogenic", "Obstructive only"], "correct_index": 0, "explanation": "Vasodilation and maldistribution define distributive shock.", "source_ref": "pathophysiology"},
        {"id": "wb-raas-chf", "title": "RAAS Activation in CHF", "trigger": "Decreased cardiac output", "normal_function": "RAAS maintains BP through sodium and water retention", "breakdown": "Compensation becomes maladaptive → volume overload → pulmonary edema", "cascade": ["Increased preload", "Crackles", "Dyspnea", "Decompensation"], "clinical_signs": ["Weight gain 2 lb/day", "Crackles", "Orthopnea"], "nursing_response": "Daily weights, diuretics, sodium restriction, notify for acute dyspnea", "question": "Which daily finding best tracks fluid status in CHF?", "options": ["Daily weight", "Single BP reading", "Pain score", "Temperature"], "correct_index": 0, "explanation": "2–3 lb gain in days signals fluid retention.", "source_ref": "pathophysiology"},
        {"id": "wb-copd-co2", "title": "CO₂ Retention in COPD", "trigger": "Exacerbation with excessive O₂", "normal_function": "Hypoxic drive maintains ventilation in chronic CO₂ retainers", "breakdown": "Over-oxygenation may suppress drive → rising PaCO₂ and acidosis", "cascade": ["Somnolence", "CO₂ narcosis", "Respiratory failure"], "clinical_signs": ["Decreased RR despite hypoxemia history", "Headache, confusion"], "nursing_response": "Titrate O₂ to SpO₂ 88–92%; ABG monitoring", "question": "Target SpO₂ for COPD exacerbation is typically:", "options": ["88–92%", "100%", "70%", "95–100%"], "correct_index": 0, "explanation": "Avoid over-oxygenation in chronic retainers.", "source_ref": "pathophysiology"},
        {"id": "wb-aki-prerenal", "title": "Prerenal AKI from Dehydration", "trigger": "Vomiting and diarrhea in elderly", "normal_function": "Kidneys autoregulate perfusion via RAAS", "breakdown": "Hypoperfusion → GFR drop → BUN rises disproportionately", "cascade": ["Oliguria", "BUN:Cr >20:1", "Responds to fluids"], "clinical_signs": ["Dry mucosa", "Orthostasis", "Oliguria"], "nursing_response": "IV fluids per order; strict I&O; hold nephrotoxic drugs", "question": "Prerenal AKI often improves with:", "options": ["Volume restoration", "Immediate dialysis always", "High-dose diuretics alone", "NPO only"], "correct_index": 0, "explanation": "Restore renal perfusion if intrinsic kidney intact.", "source_ref": "pathophysiology"},
    ]
    flashcards = []
    fc_data = [
        ("fc-1", "Left-sided heart failure", "Pulmonary congestion — crackles, orthopnea, pink frothy sputum", "Cardiovascular"),
        ("fc-2", "Right-sided heart failure", "Peripheral edema, JVD, hepatomegaly", "Cardiovascular"),
        ("fc-3", "Hypovolemic shock", "Flat JVD early, tachycardia, responds to fluid bolus", "Shock"),
        ("fc-4", "Cardiogenic shock", "JVD, crackles, poor forward flow — fluids cautious", "Shock"),
        ("fc-5", "Septic shock", "Distributive — warm then cold; MAP ≥65 goal", "Shock"),
        ("fc-6", "DKA", "Hyperglycemia + ketones + metabolic acidosis", "Endocrine"),
        ("fc-7", "COPD O₂ target", "SpO₂ 88–92%; monitor ABG baseline — avoid over-O₂", "Respiratory"),
        ("fc-8", "ARDS Berlin criteria", "P/F <300 with PEEP ≥5 and bilateral infiltrates", "Respiratory"),
        ("fc-9", "Prerenal AKI", "BUN:Cr >20:1, urine Na <20, responds to fluids", "Renal"),
        ("fc-10", "Late decelerations (OB crossover)", "Uteroplacental insufficiency — stop oxytocin, resuscitation", "Perfusion"),
        ("fc-11", "DKA insulin hold", "Hold insulin if K⁺ <3.3 mEq/L until replaced", "Endocrine"),
        ("fc-12", "Stroke priority", "Last known well; CT before thrombolytics; NPO", "Neurological"),
        ("fc-13", "HIT", "Low platelets + thrombosis on heparin — stop heparin", "Hematology"),
        ("fc-14", "Metabolic acidosis", "Kussmaul respirations; anion gap if MUDPILES", "Acid-Base"),
        ("fc-15", "Hyperkalemia ECG", "Peaked T → wide QRS → sine wave", "Electrolytes"),
        ("fc-16", "Hypokalemia", "U waves, flat T, digoxin toxicity risk", "Electrolytes"),
        ("fc-17", "HHNS", "Extreme hyperglycemia, hyperosmolarity, minimal ketones", "Endocrine"),
        ("fc-18", "Pneumonia", "Alveolar consolidation — O₂, antibiotics, IS", "Respiratory"),
        ("fc-19", "ARDS management", "Low tidal volume; prone positioning if ordered", "Respiratory"),
        ("fc-20", "Sepsis screening", "qSOFA: RR ≥22, altered mentation, SBP ≤100", "Shock"),
        ("fc-21", "Compensation", "RAAS retains Na/H₂O in low CO states", "Cardiovascular"),
        ("fc-22", "Intranrenal AKI", "Muddy brown casts; may need dialysis", "Renal"),
        ("fc-23", "qSOFA use", "Screening tool — not sole sepsis diagnosis", "Shock"),
        ("fc-24", "Asthma silent chest", "Impending respiratory failure — not improvement", "Respiratory"),
        ("fc-25", "Anemia effect on O₂", "Reduced CaO₂ despite normal SpO₂ possible", "Oxygenation"),
    ]
    for fid, front, back, cat in fc_data:
        flashcards.append({"id": fid, "front": front, "back": back, "category": cat, "clinical_why": back, "source_ref": "pathophysiology"})
    practice_questions = [
        mcq("patho-q1", "Which shock type presents with warm flushed skin early then hypotension?", ["Distributive (septic)", "Cardiogenic", "Hypovolemic", "Neurogenic only"], 0, "Septic shock early warm phase from vasodilation.", source_key="pathophysiology"),
        mcq("patho-q2", "JVD and bilateral crackles suggest:", ["Cardiogenic shock/left HF", "Hypovolemic shock", "Isolated pneumonia only", "DKA"], 0, "Fluid overload and pump failure — fluids cautiously.", source_key="pathophysiology"),
        mcq("patho-q3", "First intervention in DKA after IV access:", ["Regular insulin bolus before fluids", "IV fluid resuscitation", "IV K⁺ push", "Oral fluids only"], 1, "Fluids restore perfusion; insulin after K⁺ checked.", source_key="pathophysiology"),
        mcq("patho-q4", "Hold insulin in DKA when K⁺ is:", ["5.0 mEq/L", "4.0 mEq/L", "<3.3 mEq/L", "6.5 mEq/L"], 2, "Insulin drives K⁺ into cells — hypokalemia risk.", source_key="pathophysiology"),
        mcq("patho-q5", "COPD chronic baseline may include:", ["Compensated respiratory acidosis", "Primary metabolic alkalosis only", "Normal PaCO₂ always", "Metabolic acidosis only"], 0, "Chronic retainers compensate with elevated HCO₃⁻.", source_key="pathophysiology"),
        mcq("patho-q6", "Refractory hypotension in septic shock after fluids — next:", ["Large fluid bolus only", "Vasopressor per protocol", "Immediate discharge", "Oral hydration"], 1, "Norepinephrine often first-line for MAP ≥65.", source_key="pathophysiology"),
        mcq("patho-q7", "Prerenal AKI BUN:Cr ratio typically:", [">20:1", "<10:1", "Exactly 1:1", "Not useful"], 0, "BUN rises disproportionately with prerenal azotemia.", source_key="pathophysiology"),
        mcq("patho-q8", "Before thrombolytics in suspected stroke:", ["MRI only", "CT head to rule out hemorrhage", "Lumbar puncture first", "Start heparin drip"], 1, "Hemorrhagic stroke contraindicates thrombolytics.", source_key="pathophysiology"),
        mcq("patho-q9", "Hyperkalemia ECG progression includes:", ["Peaked T waves", "U waves only", "ST elevation MI pattern only", "Normal ECG until arrest"], 0, "Peaked T earliest — then QRS widening.", source_key="pathophysiology"),
        mcq("patho-q10", "Daily weight gain of 2 lb in CHF signals:", ["Improved nutrition", "Fluid retention", "Muscle gain", "Dry weight loss"], 1, "Fluid retention before crackles worsen.", source_key="pathophysiology"),
        mcq("patho-q11", "DKA vs HHNS: ketones are prominent in:", ["DKA", "HHNS", "Both equally", "Neither"], 0, "HHNS: extreme glucose without significant ketosis.", source_key="pathophysiology"),
        mcq("patho-q12", "ARDS P/F ratio Berlin definition uses PEEP:", ["≥5 cm H₂O", "0 only", "≥15 only", "Not part of criteria"], 0, "Berlin requires PEEP ≥5 with bilateral infiltrates.", source_key="pathophysiology"),
        mcq("patho-q13", "HIT on heparin — priority action:", ["Continue heparin", "Stop heparin and notify provider", "Increase heparin rate", "Platelet transfusion always"], 1, "Immune-mediated thrombosis despite low platelets.", source_key="pathophysiology"),
        mcq("patho-q14", "Left-sided HF classic finding:", ["Peripheral pitting edema only", "Pulmonary crackles and orthopnea", "JVD without lung findings", "Isolated hepatomegaly"], 1, "Pulmonary congestion from left failure.", source_key="pathophysiology"),
        mcq("patho-q15", "Metabolic acidosis compensation:", ["Increased respiratory rate (Kussmaul)", "Bradypnea", "Metabolic alkalosis always", "No compensation possible"], 0, "Blow off CO₂ to raise pH.", source_key="pathophysiology"),
        mcq("patho-q16", "Sepsis-3 definition emphasizes:", ["SIRS criteria only", "Infection with organ dysfunction", "WBC >15000 only", "Temperature spike alone"], 1, "Organ dysfunction and lactate guide management.", source_key="pathophysiology"),
        mcq("patho-q17", "Stroke penumbra is:", ["Irreversibly infarcted tissue", "Potentially salvageable ischemic tissue", "Hemorrhagic cavity", "Normal tissue"], 1, "Time-sensitive reperfusion saves penumbra.", source_key="pathophysiology"),
        mcq("patho-q18", "K⁺ 6.8 mEq/L — priority nursing action:", ["IV K⁺ push", "Continuous cardiac monitoring and notify provider", "Oral K⁺ only without assessment", "Discharge"], 1, "Cardiac arrest risk — calcium gluconate per order for membrane stabilization.", source_key="pathophysiology"),
    ]
    return {
        "module_id": "pathophysiology",
        "title": "Pathophysiology",
        "core_concepts": core_concepts,
        "disease_processes": disease_processes,
        "compare_contrast_pairs": compare_contrast_pairs,
        "what_breaks_down_scenarios": what_breaks_down_scenarios,
        "flashcards": flashcards,
        "practice_questions": practice_questions,
        "source": s,
    }