"""Build terminology.json."""
from __future__ import annotations

from typing import Any

from scripts.restore_content_payload.common import mcq, src


def build() -> dict[str, Any]:
    s = src("terminology")
    prefixes = [
        {"element": "a-", "meaning": "without, not", "examples": ["apnea", "anuria", "asystole"], "clinical_note": "Absence or lack — e.g., apnea = without breathing.", "source": s},
        {"element": "an-", "meaning": "without, not", "examples": ["anemia", "anesthesia"], "clinical_note": "Same as a- before vowels.", "source": s},
        {"element": "anti-", "meaning": "against", "examples": ["antibiotic", "anticoagulant", "antipyretic"], "clinical_note": "Drug classes often use anti- prefix.", "source": s},
        {"element": "bi-", "meaning": "two, double", "examples": ["bilateral", "bicuspid"], "clinical_note": "Bilateral findings compare both sides.", "source": s},
        {"element": "brady-", "meaning": "slow", "examples": ["bradycardia", "bradypnea"], "clinical_note": "Bradycardia <60 bpm — assess symptoms.", "source": s},
        {"element": "contra-", "meaning": "against, opposite", "examples": ["contraindication"], "clinical_note": "Contraindication = reason to avoid treatment.", "source": s},
        {"element": "de-", "meaning": "down, removal", "examples": ["dehydration", "debridement"], "clinical_note": "Dehydration = fluid deficit.", "source": s},
        {"element": "dia-", "meaning": "through, across", "examples": ["diagnosis", "diuretic"], "clinical_note": "Diuretic promotes urine flow through kidneys.", "source": s},
        {"element": "dis-", "meaning": "apart, reversal", "examples": ["dislocation", "disinfectant"], "clinical_note": "Dis- indicates separation or negation.", "source": s},
        {"element": "dys-", "meaning": "difficult, painful, abnormal", "examples": ["dyspnea", "dysphagia", "dysuria"], "clinical_note": "Dys- symptoms warrant focused assessment.", "source": s},
        {"element": "ecto-", "meaning": "outside", "examples": ["ectopic pregnancy"], "clinical_note": "Ectopic = outside normal location.", "source": s},
        {"element": "endo-", "meaning": "within, inner", "examples": ["endocardium", "endoscopy"], "clinical_note": "Endoscopy visualizes internal structures.", "source": s},
        {"element": "epi-", "meaning": "upon, over", "examples": ["epidural", "epistaxis"], "clinical_note": "Epidural = outside dura mater.", "source": s},
        {"element": "hemi-", "meaning": "half", "examples": ["hemiplegia", "hemisphere"], "clinical_note": "Hemiplegia = paralysis on one side.", "source": s},
        {"element": "hyper-", "meaning": "excessive, above", "examples": ["hypertension", "hyperglycemia"], "clinical_note": "Hyper- states often need monitoring and treatment.", "source": s},
        {"element": "hypo-", "meaning": "deficient, below", "examples": ["hypotension", "hypoglycemia"], "clinical_note": "Hypoglycemia <70 mg/dL — treat immediately.", "source": s},
        {"element": "intra-", "meaning": "within", "examples": ["intravenous", "intramuscular"], "clinical_note": "Parenteral routes use intra- prefixes.", "source": s},
        {"element": "macro-", "meaning": "large", "examples": ["macrocephaly", "macrocytic"], "clinical_note": "Macro- describes enlarged structures.", "source": s},
        {"element": "micro-", "meaning": "small", "examples": ["microcephaly", "microorganism"], "clinical_note": "Micro- used in microbiology and lab terms.", "source": s},
        {"element": "neo-", "meaning": "new", "examples": ["neonatal", "neoplasm"], "clinical_note": "Neonatal = newborn period.", "source": s},
        {"element": "peri-", "meaning": "around, surrounding", "examples": ["pericardium", "perioperative"], "clinical_note": "Perioperative care spans before/during/after surgery.", "source": s},
        {"element": "poly-", "meaning": "many, much", "examples": ["polyuria", "polycythemia"], "clinical_note": "Polyuria classic in hyperglycemia.", "source": s},
        {"element": "post-", "meaning": "after", "examples": ["postoperative", "postpartum"], "clinical_note": "Postpartum = after delivery.", "source": s},
        {"element": "pre-", "meaning": "before", "examples": ["prenatal", "premedication"], "clinical_note": "Prenatal care supports maternal-fetal health.", "source": s},
        {"element": "sub-", "meaning": "under, below", "examples": ["subcutaneous", "sublingual"], "clinical_note": "Subcutaneous = beneath skin.", "source": s},
        {"element": "super-", "meaning": "above, excessive", "examples": ["superior", "superficial"], "clinical_note": "Superior = toward head (anatomical).", "source": s},
        {"element": "tachy-", "meaning": "fast, rapid", "examples": ["tachycardia", "tachypnea"], "clinical_note": "Tachycardia >100 bpm at rest.", "source": s},
        {"element": "trans-", "meaning": "across, through", "examples": ["transfusion", "transdermal"], "clinical_note": "Transdermal patches deliver drug through skin.", "source": s},
        {"element": "uni-", "meaning": "one", "examples": ["unilateral", "unipolar"], "clinical_note": "Unilateral weakness suggests focal neuro deficit.", "source": s},
    ]
    roots = [
        {"element": "cardi", "meaning": "heart", "examples": ["cardiology", "cardiomegaly", "tachycardia"], "clinical_note": "Cardiac terms link to hemodynamics and ECG.", "source": s},
        {"element": "cerebr", "meaning": "brain", "examples": ["cerebral", "cerebrovascular"], "clinical_note": "Cerebral perfusion critical in stroke/TBI.", "source": s},
        {"element": "col", "meaning": "colon", "examples": ["colitis", "colonoscopy"], "clinical_note": "Col- terms relate to large intestine.", "source": s},
        {"element": "crani", "meaning": "skull", "examples": ["craniotomy"], "clinical_note": "Craniotomy accesses brain — ICP precautions.", "source": s},
        {"element": "cyan", "meaning": "blue", "examples": ["cyanosis"], "clinical_note": "Cyanosis signals hypoxemia.", "source": s},
        {"element": "derm", "meaning": "skin", "examples": ["dermatitis", "epidermis"], "clinical_note": "Integumentary assessment uses derm roots.", "source": s},
        {"element": "enter", "meaning": "intestine", "examples": ["gastroenterology", "enteral"], "clinical_note": "Enteral feeding uses GI tract.", "source": s},
        {"element": "gastr", "meaning": "stomach", "examples": ["gastritis", "gastroscopy"], "clinical_note": "Gastric emptying affects oral meds.", "source": s},
        {"element": "hemat", "meaning": "blood", "examples": ["hematuria", "hematology"], "clinical_note": "Hemat- terms involve CBC and transfusion.", "source": s},
        {"element": "hepat", "meaning": "liver", "examples": ["hepatitis", "hepatic"], "clinical_note": "Hepatic function guides drug dosing.", "source": s},
        {"element": "laryng", "meaning": "larynx (voice box)", "examples": ["laryngitis", "laryngoscope"], "clinical_note": "Laryng- relates to airway patency.", "source": s},
        {"element": "leuk", "meaning": "white", "examples": ["leukemia", "leukocytosis"], "clinical_note": "Leukocytes fight infection.", "source": s},
        {"element": "mening", "meaning": "membrane (often meninges)", "examples": ["meningitis"], "clinical_note": "Meningitis = meningeal inflammation — neuro emergency.", "source": s},
        {"element": "my/o", "meaning": "muscle", "examples": ["myopathy", "myocardium"], "clinical_note": "My/o used in cardiac and musculoskeletal terms.", "source": s},
        {"element": "nephr", "meaning": "kidney", "examples": ["nephritis", "nephrology"], "clinical_note": "Renal function affects fluid and electrolytes.", "source": s},
        {"element": "neur", "meaning": "nerve", "examples": ["neurology", "neuropathy"], "clinical_note": "Neuro checks use neur- vocabulary.", "source": s},
        {"element": "onc", "meaning": "tumor, mass", "examples": ["oncology", "oncologist"], "clinical_note": "Onc- terms in cancer care pathways.", "source": s},
        {"element": "oste", "meaning": "bone", "examples": ["osteoporosis", "osteomyelitis"], "clinical_note": "Osteoporosis increases fracture risk.", "source": s},
        {"element": "path", "meaning": "disease", "examples": ["pathology", "pathogenesis"], "clinical_note": "Pathophysiology = disease + function.", "source": s},
        {"element": "phleb", "meaning": "vein", "examples": ["phlebitis", "phlebotomy"], "clinical_note": "Phlebitis at IV site — rotate sites.", "source": s},
        {"element": "pneumon", "meaning": "lung", "examples": ["pneumonia", "pneumothorax"], "clinical_note": "Pneumon- terms in respiratory disorders.", "source": s},
        {"element": "psych", "meaning": "mind", "examples": ["psychiatry", "psychosis"], "clinical_note": "Psychosocial integrity on NCLEX.", "source": s},
        {"element": "pulmon", "meaning": "lung", "examples": ["pulmonology", "pulmonary"], "clinical_note": "Pulmonary = pertaining to lungs.", "source": s},
        {"element": "ren", "meaning": "kidney", "examples": ["renal", "renin"], "clinical_note": "Renal dose adjustments common.", "source": s},
        {"element": "rhin", "meaning": "nose", "examples": ["rhinitis", "rhinorrhea"], "clinical_note": "Rhinorrhea = runny nose.", "source": s},
        {"element": "thorac", "meaning": "chest", "examples": ["thoracentesis", "thoracotomy"], "clinical_note": "Thoracic procedures need respiratory monitoring.", "source": s},
        {"element": "thromb", "meaning": "clot", "examples": ["thrombosis", "thrombocytopenia"], "clinical_note": "Thrombocytopenia increases bleeding risk.", "source": s},
        {"element": "trache", "meaning": "trachea", "examples": ["tracheostomy", "tracheitis"], "clinical_note": "Tracheostomy requires airway suctioning skills.", "source": s},
        {"element": "ur", "meaning": "urine, urinary", "examples": ["urinalysis", "urology"], "clinical_note": "Ur- terms in GU assessment.", "source": s},
        {"element": "vas", "meaning": "vessel", "examples": ["vasodilator", "vascular"], "clinical_note": "Vascular terms in cardiovascular pharmacology.", "source": s},
    ]
    suffixes = [
        {"element": "-algia", "meaning": "pain", "examples": ["neuralgia", "myalgia"], "clinical_note": "Algia suffix = pain condition.", "source": s},
        {"element": "-cele", "meaning": "hernia, swelling, sac", "examples": ["hydrocele", "meningocele"], "clinical_note": "Cele indicates protrusion or fluid sac.", "source": s},
        {"element": "-centesis", "meaning": "surgical puncture to remove fluid", "examples": ["thoracentesis", "amniocentesis"], "clinical_note": "Informed consent required.", "source": s},
        {"element": "-ectomy", "meaning": "surgical removal", "examples": ["appendectomy", "mastectomy"], "clinical_note": "Post-op nursing priorities after -ectomy.", "source": s},
        {"element": "-emia", "meaning": "blood condition", "examples": ["anemia", "bacteremia", "hyperglycemia"], "clinical_note": "-emia often appears on lab reports.", "source": s},
        {"element": "-genic", "meaning": "producing, originating", "examples": ["carcinogenic", "iatrogenic"], "clinical_note": "Iatrogenic = caused by medical treatment.", "source": s},
        {"element": "-gram", "meaning": "record, image", "examples": ["electrocardiogram", "mammogram"], "clinical_note": "Diagnostic imaging and tracings.", "source": s},
        {"element": "-graphy", "meaning": "process of recording", "examples": ["mammography", "radiography"], "clinical_note": "Screening tests use -graphy.", "source": s},
        {"element": "-itis", "meaning": "inflammation", "examples": ["gastritis", "arthritis", "meningitis"], "clinical_note": "Most common disease suffix in med-surg.", "source": s},
        {"element": "-logy", "meaning": "study of", "examples": ["cardiology", "pathology"], "clinical_note": "-logy denotes medical specialty.", "source": s},
        {"element": "-lysis", "meaning": "breakdown, separation, destruction", "examples": ["hemodialysis", "paralysis"], "clinical_note": "Dialysis removes waste via -lysis.", "source": s},
        {"element": "-malacia", "meaning": "softening", "examples": ["osteomalacia", "tracheomalacia"], "clinical_note": "Malacia = abnormal softening of tissue.", "source": s},
        {"element": "-oma", "meaning": "tumor, mass", "examples": ["carcinoma", "hematoma"], "clinical_note": "Not all -oma are malignant.", "source": s},
        {"element": "-osis", "meaning": "condition, disease process", "examples": ["cyanosis", "stenosis", "ketoacidosis"], "clinical_note": "Describes abnormal states.", "source": s},
        {"element": "-ostomy", "meaning": "surgical opening", "examples": ["colostomy", "tracheostomy"], "clinical_note": "Stoma care is nursing responsibility.", "source": s},
        {"element": "-otomy", "meaning": "surgical incision", "examples": ["laparotomy", "craniotomy"], "clinical_note": "-otomy = cut into; -ectomy = remove.", "source": s},
        {"element": "-pathy", "meaning": "disease", "examples": ["neuropathy", "cardiomyopathy"], "clinical_note": "-pathy = disease of an organ/tissue.", "source": s},
        {"element": "-penia", "meaning": "deficiency", "examples": ["leukopenia", "thrombocytopenia"], "clinical_note": "Penia = low count — bleeding/infection risk.", "source": s},
        {"element": "-pexy", "meaning": "surgical fixation", "examples": ["nephropexy"], "clinical_note": "Pexy stabilizes mobile organs.", "source": s},
        {"element": "-plasty", "meaning": "surgical repair", "examples": ["angioplasty", "rhinoplasty"], "clinical_note": "Plasty = reconstructive procedure.", "source": s},
        {"element": "-rrhage", "meaning": "bursting forth (hemorrhage)", "examples": ["hemorrhage", "menorrhagia"], "clinical_note": "Hemorrhage = active bleeding — priority.", "source": s},
        {"element": "-rrhea", "meaning": "flow, discharge", "examples": ["diarrhea", "rhinorrhea"], "clinical_note": "Rrhea = abnormal flow.", "source": s},
        {"element": "-scope", "meaning": "instrument for viewing", "examples": ["endoscope", "stethoscope"], "clinical_note": "-scopy procedures often require NPO.", "source": s},
        {"element": "-scopy", "meaning": "visual examination", "examples": ["colonoscopy", "bronchoscopy"], "clinical_note": "Post-procedure monitoring required.", "source": s},
        {"element": "-stasis", "meaning": "stopping, standing still", "examples": ["hemostasis", "biliary stasis"], "clinical_note": "Stasis can promote clot or infection.", "source": s},
        {"element": "-tomy", "meaning": "incision, cutting", "examples": ["laparotomy", "phlebotomy"], "clinical_note": "Phlebotomy = venipuncture for labs.", "source": s},
    ]
    practice_questions = [
        mcq("term-q01", "The prefix 'brady-' in bradycardia means:", ["Fast", "Slow", "Irregular", "Absent"], 1, "Brady- = slow. Bradycardia is heart rate <60 bpm at rest.", clinical_why="Symptomatic bradycardia may need atropine per ACLS.", nclex_category="Reduction of Risk Potential", source_key="terminology"),
        mcq("term-q02", "Which suffix means inflammation?", ["-osis", "-itis", "-emia", "-logy"], 1, "-itis = inflammation (gastritis, meningitis).", source_key="terminology"),
        mcq("term-q03", "Hematuria means:", ["Blood in urine", "Excess protein in urine", "Scant urine output", "Painful urination"], 0, "Hemat (blood) + -uria (urine condition).", clinical_why="Report gross or microscopic hematuria to provider.", source_key="terminology"),
        mcq("term-q04", "The root 'nephr' refers to the:", ["Liver", "Kidney", "Lung", "Heart"], 1, "Nephr/o = kidney — nephrology, nephritis.", source_key="terminology"),
        mcq("term-q05", "Hyperglycemia indicates:", ["Low blood sugar", "High blood sugar", "Low blood pressure", "High heart rate"], 1, "Hyper- (excessive) + glyc (glucose) + -emia.", clinical_why="Assess for DKA/HHS; verify insulin orders.", source_key="terminology"),
        mcq("term-q06", "An antibiotic is best defined as:", ["Against life (etymology only)", "A drug that inhibits or destroys bacteria", "A drug that widens bronchi", "A drug that promotes urination"], 1, "Anti- + bio + -tic — clinically: antibacterial agent.", source_key="terminology"),
        mcq("term-q07", "Thrombocytopenia means:", ["High platelet count", "Low platelet count", "High white count", "Blood clot in vein"], 1, "Thromb/o (clot/platelet) + cyt (cell) + -penia (deficiency).", clinical_why="Bleeding precautions; monitor for petechiae.", source_key="terminology"),
        mcq("term-q08", "The prefix 'dys-' in dyspnea means:", ["Without", "Difficult or painful", "Fast", "Above normal"], 1, "Dys- = difficult — dyspnea = labored breathing.", source_key="terminology"),
        mcq("term-q09", "Which term means surgical removal?", ["-ostomy", "-ectomy", "-scopy", "-centesis"], 1, "-ectomy = excision (appendectomy).", source_key="terminology"),
        mcq("term-q10", "Leukocytosis indicates:", ["Decreased white blood cells", "Elevated white blood cells", "Low red blood cells", "Clot formation"], 1, "Leuk/o + cyt + -osis — often infection or inflammation.", source_key="terminology"),
        mcq("term-q11", "Subcutaneous means:", ["Within a vein", "Beneath the skin", "Within a muscle", "Within the skull"], 1, "Sub- (under) + cutane (skin) + -ous.", source_key="terminology"),
        mcq("term-q12", "Pathogenesis refers to:", ["Study of disease cause (etiology)", "Development of disease", "Prediction of disease course", "Identification of disease"], 1, "Path/o + -genesis (origin) = how disease develops.", source_key="terminology"),
        mcq("term-q13", "The root 'psych' relates to:", ["Lungs", "Mind", "Bone", "Stomach"], 1, "Psych/o = mind — psychiatry, psychosis.", source_key="terminology"),
        mcq("term-q14", "Contraindication means:", ["Reason to use a treatment", "Reason to avoid a treatment", "Side effect of medication", "Normal finding"], 1, "Contra- (against) + indication.", clinical_why="Always assess before administering.", source_key="terminology"),
        mcq("term-q15", "Oliguria is best defined as:", ["Excessive urination", "Scant urine output", "Blood in urine", "Absence of all urine forever"], 1, "Olig/o (scant) + ur + -ia — output well below normal.", clinical_why="<30 mL/hr in adults warrants assessment for AKI.", source_key="terminology"),
        mcq("term-q16", "Which prefix means within?", ["Extra-", "Intra-", "Peri-", "Sub-"], 1, "Intra- = within (intravenous, intramuscular).", source_key="terminology"),
        mcq("term-q17", "A bronchodilator is:", ["A medication that causes bronchodilation", "Inflammation of bronchi", "Surgical lung removal", "Rapid breathing"], 0, "Agent class, not the process itself.", source_key="terminology"),
        mcq("term-q18", "Nosocomial infection originates:", ["In the community", "In the hospital/healthcare setting", "From food only", "From genetics"], 1, "Nosocom- (hospital) + -ial.", clinical_why="HAIs require infection control bundles.", source_key="terminology"),
    ]
    flashcards = [
        {"id": "term-fc-01", "front": "tachy-", "back": "fast, rapid", "category": "prefix", "clinical_why": "Tachycardia >100 bpm — assess cause (pain, fever, hypovolemia).", "source": s},
        {"id": "term-fc-02", "front": "brady-", "back": "slow", "category": "prefix", "clinical_why": "Bradycardia may be normal in athletes if asymptomatic.", "source": s},
        {"id": "term-fc-03", "front": "hyper-", "back": "excessive, above normal", "category": "prefix", "clinical_why": "Hyperkalemia affects cardiac conduction — ECG changes.", "source": s},
        {"id": "term-fc-04", "front": "hypo-", "back": "deficient, below normal", "category": "prefix", "clinical_why": "Hypoglycemia: 15 g fast carbs, recheck in 15 min.", "source": s},
        {"id": "term-fc-05", "front": "cardi", "back": "heart", "category": "root", "clinical_why": "Cardiac output = HR × stroke volume.", "source": s},
        {"id": "term-fc-06", "front": "pneumon", "back": "lung", "category": "root", "clinical_why": "Pneumonia = alveolar consolidation — O₂ and IS.", "source": s},
        {"id": "term-fc-07", "front": "nephr", "back": "kidney", "category": "root", "clinical_why": "Monitor BUN/creatinine and I&O.", "source": s},
        {"id": "term-fc-08", "front": "hepat", "back": "liver", "category": "root", "clinical_why": "Hepatic impairment alters drug metabolism.", "source": s},
        {"id": "term-fc-09", "front": "-itis", "back": "inflammation", "category": "suffix", "clinical_why": "Assess for infection vs autoimmune cause.", "source": s},
        {"id": "term-fc-10", "front": "-ectomy", "back": "surgical removal", "category": "suffix", "clinical_why": "Pre-op verification and post-op complications.", "source": s},
        {"id": "term-fc-11", "front": "-emia", "back": "blood condition", "category": "suffix", "clinical_why": "Bacteremia/sepsis require urgent intervention.", "source": s},
        {"id": "term-fc-12", "front": "-penia", "back": "deficiency", "category": "suffix", "clinical_why": "Leukopenia → neutropenic precautions.", "source": s},
        {"id": "term-fc-13", "front": "dys-", "back": "difficult, painful, abnormal", "category": "prefix", "clinical_why": "Dysphagia increases aspiration risk.", "source": s},
        {"id": "term-fc-14", "front": "poly-", "back": "many, much", "category": "prefix", "clinical_why": "Polyuria classic sign of hyperglycemia.", "source": s},
        {"id": "term-fc-15", "front": "a-/an-", "back": "without, not", "category": "prefix", "clinical_why": "Anuria/oliguria signal renal emergency.", "source": s},
        {"id": "term-fc-16", "front": "intra-", "back": "within", "category": "prefix", "clinical_why": "IV route — verify 5 Rights.", "source": s},
        {"id": "term-fc-17", "front": "sub-", "back": "under", "category": "prefix", "clinical_why": "Subcutaneous insulin — rotate sites.", "source": s},
        {"id": "term-fc-18", "front": "hemat", "back": "blood", "category": "root", "clinical_why": "Hematuria, anemia, hematology panels.", "source": s},
        {"id": "term-fc-19", "front": "oste", "back": "bone", "category": "root", "clinical_why": "Osteoporosis — fall prevention.", "source": s},
        {"id": "term-fc-20", "front": "-scopy", "back": "visual examination", "category": "suffix", "clinical_why": "NPO and consent before endoscopy.", "source": s},
        {"id": "term-fc-21", "front": "-ostomy", "back": "surgical opening", "category": "suffix", "clinical_why": "Stoma assessment and patient teaching.", "source": s},
        {"id": "term-fc-22", "front": "-pathy", "back": "disease", "category": "suffix", "clinical_why": "Diabetic neuropathy — foot exams.", "source": s},
    ]
    return {
        "module_id": "terminology",
        "title": "Medical Terminology",
        "prefixes": prefixes,
        "roots": roots,
        "suffixes": suffixes,
        "practice_questions": practice_questions,
        "flashcards": flashcards,
        "source": s,
    }