#!/usr/bin/env python3
"""Generate terminology_terms.json with 150+ verified nursing terms."""
import json
from pathlib import Path

SOURCE = {
    "title": "Medical Terminology for Health Professions",
    "citation": "Ehrlich & Schroeder, 8th Ed.",
    "verified_date": "2026-06",
}

# (term, definition, category, prefix, root, suffix, breakdown, clinical)
CURATED = [
    ("tachycardia", "Abnormally rapid heart rate (>100 bpm at rest)", "disease", "tachy-", "cardi", "-ia", "tachy (fast) + cardi (heart) + -ia", "Monitor vitals; assess chest pain, fever, dehydration."),
    ("bradycardia", "Abnormally slow heart rate (<60 bpm at rest)", "disease", "brady-", "cardi", "-ia", "brady (slow) + cardi + -ia", "May be normal in athletes; symptomatic bradycardia needs intervention."),
    ("hypertension", "Persistently elevated BP above 130/80 mmHg", "disease", "hyper-", "tens", "-ion", "hyper (excessive) + tens (pressure)", "Leading risk for stroke and MI; often asymptomatic."),
    ("hypotension", "Abnormally low blood pressure", "disease", "hypo-", "tens", "-ion", "hypo (low) + tens (pressure)", "Assess for shock; check orthostatics and fluid status."),
    ("dyspnea", "Difficult or labored breathing", "disease", "dys-", "pnea", "", "dys (difficult) + pnea (breathing)", "Check SpO2, lung sounds; position upright."),
    ("apnea", "Temporary cessation of breathing", "disease", "a-", "pnea", "", "a (without) + pnea", "Sleep apnea increases cardiovascular risk; monitor post-op."),
    ("tachypnea", "Abnormally rapid respirations", "disease", "tachy-", "pnea", "", "tachy + pnea", "Early sign of respiratory distress or metabolic acidosis."),
    ("bradypnea", "Abnormally slow respirations", "disease", "brady-", "pnea", "", "brady + pnea", "May indicate CNS depression from opioids or head injury."),
    ("hematuria", "Blood in the urine", "disease", "", "hemat", "-uria", "hemat (blood) + -uria", "Report gross or microscopic hematuria to provider."),
    ("proteinuria", "Excess protein in the urine", "disease", "", "protein", "-uria", "protein + -uria", "Key indicator of kidney damage; common in diabetes."),
    ("polyuria", "Excessive urination", "disease", "poly-", "ur", "-ia", "poly (many) + ur + -ia", "Classic sign of hyperglycemia and diabetes."),
    ("oliguria", "Scant urine output", "disease", "olig/o", "ur", "-ia", "oligo (scant) + ur + -ia", "Output <400 mL/day signals acute kidney injury."),
    ("anuria", "Absence of urine output", "disease", "an-", "ur", "-ia", "an (without) + ur + -ia", "Medical emergency; assess for obstruction or renal failure."),
    ("gastritis", "Inflammation of the stomach lining", "disease", "", "gastr", "-itis", "gastr + -itis", "NSAIDs and H. pylori are common causes."),
    ("hepatitis", "Inflammation of the liver", "disease", "", "hepat", "-itis", "hepat + -itis", "Monitor liver enzymes; types A–E differ in transmission."),
    ("nephritis", "Inflammation of the kidney", "disease", "", "nephr", "-itis", "nephr + -itis", "Monitor BUN, creatinine, and fluid balance."),
    ("dermatitis", "Inflammation of the skin", "disease", "", "derm", "-itis", "derm + -itis", "Assess triggers; contact vs atopic patterns differ."),
    ("arthritis", "Inflammation of joints", "disease", "", "arthr", "-itis", "arthr (joint) + -itis", "Assess pain, ROM, and morning stiffness."),
    ("meningitis", "Inflammation of the meninges", "disease", "", "mening", "-itis", "mening + -itis", "Nuchal rigidity and photophobia are classic signs."),
    ("pneumonia", "Infection of lung parenchyma", "disease", "", "pneumon", "-ia", "pneumon (lung) + -ia", "Assess O2, crackles; incentive spirometry helps."),
    ("sepsis", "Life-threatening organ dysfunction from infection", "disease", "", "sept", "-ia", "sept (infection) + -ia", "Time-critical; qSOFA and lactate guide escalation."),
    ("anemia", "Deficiency of red blood cells or hemoglobin", "disease", "an-", "em", "-ia", "an (without) + em (blood) + -ia", "Assess fatigue, pallor; iron studies guide treatment."),
    ("leukemia", "Cancer of blood-forming tissues", "disease", "", "leuk", "-emia", "leuk (white) + -emia", "Neutropenic precautions during chemotherapy."),
    ("leukopenia", "Low white blood cell count", "disease", "", "leuk", "-penia", "leuk + -penia (deficiency)", "ANC <500 requires neutropenic precautions."),
    ("leukocytosis", "Elevated white blood cell count", "disease", "", "leuk", "-osis", "leuk + -osis", "Often indicates infection or inflammation."),
    ("thrombocytopenia", "Low platelet count", "disease", "", "thromb/o", "-penia", "thromb (clot) + -penia", "Bleeding risk; monitor for petechiae and bruising."),
    ("hypoglycemia", "Low blood glucose (<70 mg/dL)", "disease", "hypo-", "glyc", "-emia", "hypo + glyc + -emia", "Treat immediately with 15g fast-acting carbs."),
    ("hyperglycemia", "Elevated blood glucose", "disease", "hyper-", "glyc", "-emia", "hyper + glyc + -emia", "Assess for DKA/HHS; verify insulin orders."),
    ("ketoacidosis", "Metabolic state with ketones and acidosis", "disease", "", "keto", "-osis", "keto + -osis", "DKA emergency: fluids, insulin, K+ monitoring."),
    ("cyanosis", "Bluish skin from inadequate oxygenation", "disease", "", "cyan", "-osis", "cyan (blue) + -osis", "Check SpO2; central cyanosis is more urgent."),
    ("jaundice", "Yellowing of skin from bilirubin", "disease", "", "jaund", "-ice", "jaund (yellow)", "Assess sclera; liver vs hemolytic causes differ."),
    ("edema", "Swelling from fluid accumulation", "disease", "", "edem", "-a", "edem (swelling)", "Pitting vs non-pitting; assess heart, kidney, liver."),
    ("ascites", "Abnormal fluid in peritoneal cavity", "disease", "", "ascit", "-es", "ascit (fluid)", "Common in liver cirrhosis; monitor respiratory status."),
    ("stenosis", "Abnormal narrowing of a passage", "disease", "", "sten", "-osis", "sten (narrow) + -osis", "Aortic stenosis affects cardiac output."),
    ("sclerosis", "Abnormal hardening of tissue", "disease", "", "scler", "-osis", "scler (hard) + -osis", "Multiple sclerosis affects CNS myelin."),
    ("necrosis", "Death of cells or tissue", "disease", "", "necr", "-osis", "necr (death) + -osis", "Pressure injuries can progress to necrosis."),
    ("ischemia", "Inadequate blood supply to tissue", "disease", "", "ischem", "-ia", "ischem (hold back blood)", "Chest pain may indicate myocardial ischemia."),
    ("infarction", "Death of tissue from ischemia", "disease", "", "infarct", "-ion", "infarct (plugged)", "MI and stroke are infarctions — time-critical."),
    ("embolism", "Obstruction by traveling clot/debris", "disease", "", "embol", "-ism", "embol (plug)", "PE is a leading cause of preventable death."),
    ("thrombosis", "Formation of a blood clot in a vessel", "disease", "", "thromb", "-osis", "thromb (clot) + -osis", "DVT prophylaxis is standard for immobile patients."),
    ("phlebitis", "Inflammation of a vein", "disease", "", "phleb", "-itis", "phleb + -itis", "Discontinue IV and rotate sites to prevent."),
    ("neuropathy", "Disease of peripheral nerves", "disease", "", "neur", "-pathy", "neur + -pathy", "Diabetic neuropathy — assess foot sensation."),
    ("myopathy", "Disease of muscle tissue", "disease", "", "my/o", "-pathy", "myo (muscle) + -pathy", "Statins can cause myopathy; report muscle pain."),
    ("osteoporosis", "Porous, brittle bones", "disease", "", "oste", "-porosis", "oste (bone) + porosis", "Fall prevention is critical in older adults."),
    ("osteomyelitis", "Bone infection", "disease", "", "oste", "-myelitis", "oste + myel (marrow) + -itis", "Long-term IV antibiotics often required."),
    ("scoliosis", "Lateral curvature of the spine", "disease", "", "scoli", "-osis", "scoli (crooked) + -osis", "Assess respiratory impact in severe cases."),
    ("kyphosis", "Excessive outward curvature of thoracic spine", "disease", "", "kyph", "-osis", "kyph (hump) + -osis", "Common in osteoporosis compression fractures."),
    ("lordosis", "Excessive inward lumbar curvature", "disease", "", "lord", "-osis", "lord (curve) + -osis", "Pregnancy and obesity are common causes."),
    ("hernia", "Protrusion of organ through wall", "disease", "", "herni", "-a", "herni (rupture)", "Strangulated hernia is surgical emergency."),
    ("diverticulitis", "Inflammation of colon diverticula", "disease", "", "diverticul", "-itis", "diverticul + -itis", "LLQ pain; high-fiber diet for prevention."),
    ("cholecystitis", "Inflammation of the gallbladder", "disease", "", "cholecyst", "-itis", "cholecyst + -itis", "Murphy sign positive; often post-fatty meal pain."),
    ("pancreatitis", "Inflammation of the pancreas", "disease", "", "pancreat", "-itis", "pancreat + -itis", "Severe epigastric pain radiating to back."),
    ("colitis", "Inflammation of the colon", "disease", "", "col", "-itis", "col (colon) + -itis", "C. diff colitis requires contact precautions."),
    ("cystitis", "Inflammation of the bladder", "disease", "", "cyst", "-itis", "cyst (bladder) + -itis", "Dysuria and frequency are hallmark symptoms."),
    ("urethritis", "Inflammation of the urethra", "disease", "", "urethr", "-itis", "urethr + -itis", "STD screening may be indicated."),
    ("prostatitis", "Inflammation of the prostate", "disease", "", "prostat", "-itis", "prostat + -itis", "DRE findings guide diagnosis."),
    ("endometritis", "Inflammation of uterine lining", "disease", "endo-", "metr", "-itis", "endo + metr + -itis", "Postpartum infection; monitor lochia and fever."),
    ("mastitis", "Inflammation of breast tissue", "disease", "", "mast", "-itis", "mast (breast) + -itis", "Common in breastfeeding; encourage emptying."),
    ("rhinitis", "Inflammation of nasal mucosa", "disease", "", "rhin", "-itis", "rhin (nose) + -itis", "Allergic vs infectious management differs."),
    ("sinusitis", "Inflammation of paranasal sinuses", "disease", "", "sinus", "-itis", "sinus + -itis", "Facial pain and purulent drainage."),
    ("laryngitis", "Inflammation of the larynx", "disease", "", "laryng", "-itis", "laryng + -itis", "Voice rest; assess airway patency."),
    ("bronchitis", "Inflammation of bronchi", "disease", "", "bronch", "-itis", "bronch + -itis", "Productive cough; distinguish from pneumonia."),
    ("tracheitis", "Inflammation of the trachea", "disease", "", "trache", "-itis", "trache + -itis", "Stridor warrants urgent evaluation."),
    ("cellulitis", "Skin/subcutaneous tissue infection", "disease", "", "cellul", "-itis", "cellul + -itis", "Mark borders; elevate extremity."),
    ("conjunctivitis", "Inflammation of conjunctiva", "disease", "", "conjunctiv", "-itis", "conjunctiv + -itis", "Bacterial vs viral spread precautions differ."),
    ("keratitis", "Inflammation of the cornea", "disease", "", "kerat", "-itis", "kerat (cornea) + -itis", "Contact lens wear is a risk factor."),
    ("gingivitis", "Inflammation of the gums", "disease", "", "gingiv", "-itis", "gingiv (gums) + -itis", "Oral hygiene prevents progression to periodontitis."),
    ("periodontitis", "Inflammation/destruction of periodontium", "disease", "", "periodont", "-itis", "periodont + -itis", "Linked to cardiovascular disease risk."),
    ("myocarditis", "Inflammation of heart muscle", "disease", "", "my/o", "-carditis", "myo + card + -itis", "Post-viral; monitor for heart failure."),
    ("pericarditis", "Inflammation of the pericardium", "disease", "peri-", "card", "-itis", "peri + card + -itis", "Pain worse supine, better leaning forward."),
    ("endocarditis", "Inflammation of endocardium", "disease", "endo-", "card", "-itis", "endo + card + -itis", "IV drug use is a major risk factor."),
    ("nephrology", "Study and treatment of kidney disease", "anatomy", "", "nephro", "-logy", "nephro + -logy", "Nurses track I&O and renal labs."),
    ("cardiology", "Study and treatment of heart disease", "anatomy", "", "cardi", "-logy", "cardi + -logy", "Telemetry monitoring is nursing responsibility."),
    ("neurology", "Study of nervous system disorders", "anatomy", "", "neur", "-logy", "neur + -logy", "Neuro checks q1-4h in acute settings."),
    ("pulmonology", "Study of lung disease", "anatomy", "", "pulmon", "-logy", "pulmon + -logy", "Oxygen titration and weaning protocols."),
    ("gastroenterology", "Study of digestive system", "anatomy", "", "gastr", "-entero", "-logy", "gastr + enter + -logy", "NG tube care and bowel prep education."),
    ("dermatology", "Study of skin disease", "anatomy", "", "derm", "-logy", "derm + -logy", "Wound assessment and pressure injury staging."),
    ("hematology", "Study of blood disorders", "anatomy", "", "hemat", "-logy", "hemat + -logy", "Transfusion protocols and reaction monitoring."),
    ("oncology", "Study and treatment of cancer", "anatomy", "", "onc", "-logy", "onc (tumor) + -logy", "Chemo precautions and neutropenic care."),
    ("urology", "Study of urinary tract", "anatomy", "", "ur", "-logy", "ur + -logy", "Catheter care and UTI prevention bundles."),
    ("orthopedics", "Study of musculoskeletal system", "anatomy", "", "orth", "-pedics", "orth (straight) + pedics", "Mobility, fall risk, and weight-bearing status."),
    ("intravenous", "Within or into a vein", "procedure", "intra-", "ven", "", "intra + ven", "Verify 5 Rights; monitor for infiltration."),
    ("subcutaneous", "Beneath the skin", "procedure", "sub-", "cutane", "-ous", "sub + cutane + -ous", "Insulin and heparin route; rotate sites."),
    ("intramuscular", "Within a muscle", "procedure", "intra-", "muscul", "-ar", "intra + muscul + -ar", "Aspiration no longer recommended; select site by volume."),
    ("intradermal", "Within the skin layers", "procedure", "intra-", "derm", "-al", "intra + derm + -al", "TB and allergy testing route."),
    ("endoscopy", "Visual exam with flexible scope", "procedure", "endo-", "scop", "-y", "endo + scop + -y", "NPO prep; post-procedure vitals and bleeding."),
    ("colonoscopy", "Visual exam of the colon", "procedure", "colo-", "scop", "-y", "colo + scop + -y", "Bowel prep education is nursing role."),
    ("bronchoscopy", "Visual exam of bronchi", "procedure", "", "bronch", "-scopy", "bronch + -scopy", "NPO; assess for hemorrhage post-procedure."),
    ("laparoscopy", "Visual exam of abdominal cavity", "procedure", "lapar/o", "scop", "-y", "laparo (abdomen) + scop + -y", "Minimally invasive; shoulder pain from CO2 common."),
    ("thoracentesis", "Surgical puncture to drain pleural fluid", "procedure", "thorac-", "centesis", "", "thorac + centesis (puncture)", "Improve breathing; send fluid for analysis."),
    ("paracentesis", "Surgical puncture to drain peritoneal fluid", "procedure", "", "paracentesis", "", "para + centesis", "Large-volume para requires albumin replacement."),
    ("amniocentesis", "Puncture of amnion to withdraw fluid", "procedure", "", "amni", "-centesis", "amni + centesis", "Genetic testing and lung maturity assessment."),
    ("arthrocentesis", "Joint aspiration", "procedure", "", "arthr", "-centesis", "arthr + centesis", "Diagnose septic arthritis vs gout."),
    ("appendectomy", "Surgical removal of appendix", "procedure", "", "append", "-ectomy", "append + -ectomy", "McBurney incision or laparoscopic."),
    ("cholecystectomy", "Surgical removal of gallbladder", "procedure", "", "cholecyst", "-ectomy", "cholecyst + -ectomy", "Low-fat diet post-op education."),
    ("hysterectomy", "Surgical removal of uterus", "procedure", "", "hyster", "-ectomy", "hyster + -ectomy", "Surgical menopause if ovaries removed."),
    ("mastectomy", "Surgical removal of breast", "procedure", "", "mast", "-ectomy", "mast + -ectomy", "Body image support and lymphedema education."),
    ("nephrectomy", "Surgical removal of kidney", "procedure", "", "nephr", "-ectomy", "nephrr + -ectomy", "Single kidney — monitor renal function lifelong."),
    ("colostomy", "Surgical opening into colon", "procedure", "", "col", "-ostomy", "col + -ostomy", "Stoma assessment and pouching education."),
    ("ileostomy", "Surgical opening into ileum", "procedure", "", "ile", "-ostomy", "ile + -ostomy", "High output — monitor hydration and electrolytes."),
    ("tracheostomy", "Surgical opening into trachea", "procedure", "", "trache", "-ostomy", "trache + -ostomy", "Suctioning, humidification, stoma care."),
    ("gastrostomy", "Surgical opening into stomach", "procedure", "", "gastr", "-ostomy", "gastr + -ostomy", "Tube feeding administration and site care."),
    ("thoracotomy", "Incision into the chest wall", "procedure", "", "thorac", "-otomy", "thorac + -otomy", "Post-op pain impairs deep breathing."),
    ("laparotomy", "Incision into the abdomen", "procedure", "lapar/o", "-tomy", "", "laparo + -otomy", "Assess incision and bowel function return."),
    ("craniotomy", "Incision into the skull", "procedure", "", "crani", "-otomy", "crani + -otomy", "ICP monitoring; avoid Valsalva."),
    ("biopsy", "Removal of tissue for examination", "procedure", "", "bi/o", "-psy", "bio (life) + -psy (view)", "Informed consent; monitor biopsy site bleeding."),
    ("anesthesia", "Loss of sensation", "pharmacology", "an-", "esthes", "-ia", "an + esthes (feeling) + -ia", "Pre-op NPO and allergy assessment."),
    ("analgesia", "Absence of pain sensation", "pharmacology", "an-", "alg", "-ia", "an + alg (pain) + -ia", "Pain scales guide opioid titration."),
    ("antibiotic", "Against life (bacteria)", "pharmacology", "anti-", "bi/o", "-tic", "anti + bio + -tic", "Culture before antibiotics when possible."),
    ("anticoagulant", "Against clotting", "pharmacology", "anti-", "coagul", "-ant", "anti + coagul + -ant", "Bleeding precautions; monitor INR for warfarin."),
    ("antihypertensive", "Against high blood pressure", "pharmacology", "anti-", "hypertens", "-ive", "anti + hypertens + -ive", "Orthostatic hypotension risk — rise slowly."),
    ("antipyretic", "Against fever", "pharmacology", "anti-", "pyret", "-ic", "anti + pyret (fever) + -ic", "Acetaminophen max 4g/day in adults."),
    ("antiemetic", "Against vomiting", "pharmacology", "anti-", "em", "-etic", "anti + em (vomiting) + -etic", "Give before chemotherapy as ordered."),
    ("diuretic", "Promoting urine production", "pharmacology", "", "ur", "-etic", "ur + -etic", "Monitor K+ and daily weights."),
    ("bronchodilator", "Widening of bronchi", "pharmacology", "", "bronch", "-dilator", "bronch + dilator", "Albuterol first-line for bronchospasm."),
    ("vasodilator", "Widening of blood vessels", "pharmacology", "", "vas", "-dilator", "vas + dilator", "Nitroglycerin for angina — monitor BP."),
    ("vasoconstrictor", "Narrowing of blood vessels", "pharmacology", "", "vas", "-constrictor", "vas + constrictor", "Norepinephrine in shock — tissue perfusion."),
    ("hypodermic", "Under the skin (needle)", "procedure", "hypo-", "derm", "-ic", "hypo + derm + -ic", "Correct needle length by body habitus."),
    ("epidural", "Upon/outside the dura mater", "procedure", "epi-", "dur", "-al", "epi + dur + -al", "Labor analgesia; monitor for hypotension."),
    ("spinal", "Pertaining to the spine/canal", "anatomy", "", "spin", "-al", "spin + -al", "Post-spinal headache from CSF leak."),
    ("pericardium", "Sac surrounding the heart", "anatomy", "peri-", "cardi", "-um", "peri + cardi + -um", "Pericardial effusion may cause tamponade."),
    ("endocardium", "Inner lining of the heart", "anatomy", "endo-", "cardi", "-um", "endo + cardi + -um", "Endocarditis damages valve leaflets."),
    ("myocardium", "Heart muscle layer", "anatomy", "", "my/o", "-cardium", "myo + cardium", "STEMI injures myocardium — time is muscle."),
    ("peritoneum", "Membrane lining abdominal cavity", "anatomy", "peri-", "tone", "-um", "peri + tone + -um", "Peritonitis causes rigid abdomen."),
    ("pleura", "Membrane surrounding lungs", "anatomy", "", "pleur", "-a", "pleur + -a", "Pleural effusion dulls percussion."),
    ("mediastinum", "Central thoracic compartment", "anatomy", "", "mediastin", "-um", "mediastin + -um", "Widening on CXR may indicate aortic injury."),
    ("diaphragm", "Primary muscle of respiration", "anatomy", "", "phragm", "", "phren (mind) — separates thorax/abdomen", "Paralysis affects weaning from ventilator."),
    ("alveoli", "Air sacs of the lungs", "anatomy", "", "alveol", "-i", "alveol + -i", "Gas exchange surface; surfactant prevents collapse."),
    ("trachea", "Windpipe", "anatomy", "", "trache", "-a", "trache (rough) + -a", "Midline position; deviation suggests tension pneumo."),
    ("esophagus", "Tube from pharynx to stomach", "anatomy", "", "esophag", "-us", "esophag + -us", "NG tube placement confirmed by X-ray."),
    ("duodenum", "First part of small intestine", "anatomy", "", "duoden", "-um", "duoden (twelve) + -um", "Peptic ulcers common in bulb."),
    ("jejunum", "Middle section of small intestine", "anatomy", "", "jejun", "-um", "jejun (empty) + -um", "Primary site of nutrient absorption."),
    ("ileum", "Terminal small intestine", "anatomy", "", "ile", "-um", "ile + -um", "B12 absorption requires intact ileum."),
    ("cecum", "Blind pouch at colon start", "anatomy", "", "cec", "-um", "cec + -um", "Appendix attaches at cecum."),
    ("rectum", "Terminal portion of large intestine", "anatomy", "", "rect", "-um", "rect (straight) + -um", "Digital rectal exam for prostate and occult blood."),
    ("atrium", "Upper chamber of the heart", "anatomy", "", "atri", "-um", "atri + -um", "Left atrium receives oxygenated blood from lungs."),
    ("ventricle", "Lower pumping chamber of heart", "anatomy", "", "ventricul", "-e", "ventricul + -e", "LV failure causes pulmonary edema."),
    ("aorta", "Largest artery in the body", "anatomy", "", "aort", "-a", "aort + -a", "Dissection presents with tearing chest pain."),
    ("carotid", "Major neck arteries", "anatomy", "", "carotid", "", "carotid (stupor)", "Bruit may indicate stenosis."),
    ("femoral", "Pertaining to the thigh", "anatomy", "", "femor", "-al", "femor + -al", "Common arterial access for cardiac cath."),
    ("hepatic", "Pertaining to the liver", "anatomy", "", "hepat", "-ic", "hepat + -ic", "Hepatic panel guides medication dosing."),
    ("renal", "Pertaining to the kidney", "anatomy", "", "ren", "-al", "ren + -al", "Renal dose adjustments for many drugs."),
    ("cerebral", "Pertaining to the brain", "anatomy", "", "cerebr", "-al", "cerebr + -al", "Cerebral perfusion pressure in TBI."),
    ("spinal", "Pertaining to the spine", "anatomy", "", "spin", "-al", "spin + -al", "Spinal cord injury level determines deficits."),
    ("axillary", "Pertaining to the armpit", "anatomy", "", "axill", "-ary", "axill + -ary", "Temperature route — not for accurate core temp."),
    ("buccal", "Pertaining to the cheek", "anatomy", "", "bucc", "-al", "bucc + -al", "Some medications given buccal/sublingual."),
    ("lingual", "Pertaining to the tongue", "anatomy", "", "lingu", "-al", "lingu + -al", "Airway assessment includes tongue obstruction."),
    ("otic", "Pertaining to the ear", "anatomy", "", "ot", "-ic", "ot + -ic", "Otic drops — warm to body temp before instilling."),
    ("ophthalmic", "Pertaining to the eye", "anatomy", "", "ophthalm", "-ic", "ophthalm + -ic", "Do not touch dropper to eye."),
    ("nasal", "Pertaining to the nose", "anatomy", "", "nas", "-al", "nas + -al", "Nasal cannula low-flow oxygen delivery."),
    ("oral", "Pertaining to the mouth", "anatomy", "", "or", "-al", "or + -al", "Most common medication route."),
    ("parenteral", "Outside the GI tract", "procedure", "", "par", "-enteral", "par (beside) + enteral", "IV, IM, SC routes — sterile technique."),
    ("enteral", "Within/into the GI tract", "procedure", "", "enter", "-al", "enter + -al", "NG, OG, PEG tube feeding."),
    ("supine", "Lying on the back", "anatomy", "", "supin", "-e", "supin (backward)", "Increases aspiration risk during seizures."),
    ("prone", "Lying face downward", "anatomy", "", "pron", "-e", "pron (forward)", "ARDS prone positioning improves oxygenation."),
    ("lateral", "Side-lying position", "anatomy", "", "later", "-al", "later (side) + -al", "Recovery position prevents airway obstruction."),
    ("Fowler's", "Head of bed elevated 45-90 degrees", "procedure", "", "", "", "Named position", "Reduces aspiration; eases breathing."),
    ("Trendelenburg", "Head lower than feet", "procedure", "", "", "", "Named position", "Historically for shock — limited evidence."),
    ("dorsal", "Pertaining to the back", "anatomy", "", "dors", "-al", "dors + -al", "Dorsalis pedis pulse — peripheral perfusion."),
    ("ventral", "Pertaining to the front/belly", "anatomy", "", "ventr", "-al", "ventr (belly) + -al", "Ventral hernias through abdominal wall."),
    ("proximal", "Nearer to point of origin", "anatomy", "", "proxim", "-al", "proxim + -al", "Fracture site proximal to wrist is forearm."),
    ("distal", "Farther from point of origin", "anatomy", "", "dist", "-al", "dist + -al", "Distal pulse check after cast application."),
    ("medial", "Toward midline of body", "anatomy", "", "medi", "-al", "medi + -al", "Malleolus — medial vs lateral ankle."),
    ("lateral", "Away from midline", "anatomy", "", "later", "-al", "later + -al", "Lateral incisions for surgical access."),
    ("anterior", "Front of the body", "anatomy", "", "anter", "-ior", "anter + -ior", "Anterior MI — LAD artery territory."),
    ("posterior", "Back of the body", "anatomy", "", "poster", "-ior", "poster + -ior", "Posterior tongue airway obstruction."),
    ("superior", "Above or upper", "anatomy", "super-", "", "", "super (above)", "Superior vena cava returns head/arm blood."),
    ("inferior", "Below or lower", "anatomy", "infer-", "", "", "infer (below)", "IVC returns lower body blood to heart."),
    ("bilateral", "Both sides", "anatomy", "bi-", "later", "-al", "bi (two) + later + -al", "Bilateral crackles suggest pulmonary edema."),
    ("unilateral", "One side only", "anatomy", "uni-", "later", "-al", "uni (one) + later + -al", "Unilateral weakness — stroke vs Bell palsy."),
    ("chronic", "Long duration", "disease", "", "chron", "-ic", "chron (time) + -ic", "Chronic vs acute guides treatment urgency."),
    ("acute", "Sudden onset, short duration", "disease", "", "acut", "-e", "acut (sharp)", "Acute coronary syndrome — ECG within 10 min."),
    ("benign", "Non-cancerous, mild", "disease", "", "benign", "", "benign (kind)", "Benign prostatic hyperplasia — not cancer."),
    ("malignant", "Cancerous, harmful", "disease", "", "malign", "-ant", "malign (bad) + -ant", "Malignant hypertension — organ damage risk."),
    ("metastasis", "Spread of cancer to distant sites", "disease", "", "metastas", "-is", "metastas + -is", "Bone metastasis causes pathologic fractures."),
    ("carcinoma", "Cancer arising from epithelial tissue", "disease", "", "carcin", "-oma", "carcin + -oma", "Most common cancer type overall."),
    ("sarcoma", "Cancer of connective tissue", "disease", "", "sarc", "-oma", "sarc (flesh) + -oma", "Aggressive; often affects bone and muscle."),
    ("lymphoma", "Cancer of lymphatic tissue", "disease", "", "lymph", "-oma", "lymph + -oma", "Hodgkin vs non-Hodgkin classification."),
    ("melanoma", "Cancer of pigment-producing cells", "disease", "", "melan", "-oma", "melan (black) + -oma", "ABCDE criteria for skin lesion assessment."),
    ("adenoma", "Benign glandular tumor", "disease", "", "aden", "-oma", "aden (gland) + -oma", "Colon adenoma may progress to carcinoma."),
    ("polyp", "Growth projecting from mucous membrane", "disease", "", "polyp", "", "polyp (foot)", "Removed during colonoscopy."),
    ("stenosis", "Narrowing of a tubular structure", "disease", "", "sten", "-osis", "sten + -osis", "Spinal stenosis causes neurogenic claudication."),
    ("atrophy", "Wasting or decrease in size", "disease", "a-", "troph", "-y", "a (without) + troph (nourishment)", "Muscle atrophy from immobility."),
    ("hypertrophy", "Enlargement from cell growth", "disease", "hyper-", "troph", "-y", "hyper + troph + -y", "LV hypertrophy from chronic HTN."),
    ("dilation", "Widening or stretching", "procedure", "", "dilat", "-ion", "dilat + -ion", "Cervical dilation measured in cm during labor."),
    ("constriction", "Narrowing or tightening", "disease", "", "constrict", "-ion", "constrict + -ion", "Bronchoconstriction in asthma attack."),
    ("perfusion", "Passage of blood through vessels", "procedure", "", "perfus", "-ion", "perfus + -ion", "Poor perfusion — cold, pale extremities."),
    ("dehydration", "Excessive fluid loss", "disease", "de-", "hydr", "-ation", "de + hydr + -ation", "Skin turgor and mucous membranes assess."),
    ("rehydration", "Restoration of fluid balance", "procedure", "re-", "hydr", "-ation", "re + hydr + -ation", "Oral rehydration preferred when tolerated."),
    ("homeostasis", "Stable internal equilibrium", "anatomy", "", "homeo", "-stasis", "homeo (same) + stasis", "Nursing supports physiologic balance."),
    ("pathogenesis", "Development of disease", "disease", "", "path", "-ogenesis", "path + -ogenesis", "Understanding etiology guides prevention."),
    ("etiology", "Study of disease cause", "disease", "", "eti", "-ology", "eti + -ology", "Root cause analysis in nursing diagnosis."),
    ("prognosis", "Predicted course of disease", "disease", "", "progn", "-osis", "progn + -osis", "Patient education on expected outcomes."),
    ("diagnosis", "Identification of disease", "procedure", "", "diagnos", "-is", "diagnos + -is", "NANDA-I nursing diagnoses complement medical."),
    ("symptom", "Subjective patient experience", "disease", "", "symptom", "", "symptom (occurrence)", "Pain is a symptom — subjective data."),
    ("sign", "Objective clinical finding", "disease", "", "sign", "", "sign", "Fever is a sign — objective measurement."),
    ("syndrome", "Group of symptoms occurring together", "disease", "", "syndrom", "-e", "syndrom + -e", "Metabolic syndrome — cluster of risk factors."),
    ("contraindication", "Reason to avoid a treatment", "pharmacology", "contra-", "indic", "-ation", "contra + indic + -ation", "Always check before administering."),
    ("indication", "Reason to use a treatment", "pharmacology", "", "indic", "-ation", "indic + -ation", "Evidence-based indication guides orders."),
    ("iatrogenic", "Caused by medical treatment", "disease", "", "iatr", "-ogenic", "iatr (physician) + -ogenic", "Hospital-acquired conditions are iatrogenic."),
    ("nosocomial", "Originating in the hospital", "disease", "", "nosocom", "-ial", "nosocom (hospital) + -ial", "HAIs require infection control bundles."),
    ("idiopathic", "Unknown cause", "disease", "", "idiopath", "-ic", "idio (own) + path + -ic", "Idiopathic — diagnosis of exclusion."),
    ("congenital", "Present at birth", "disease", "con-", "genit", "-al", "con + genit + -al", "Congenital heart defects need lifelong follow-up."),
    ("acquired", "Developed after birth", "disease", "", "acquir", "-ed", "acquir + -ed", "Acquired immunodeficiency — HIV/AIDS."),
    ("febrile", "Having a fever", "disease", "", "febr", "-ile", "febr (fever) + -ile", "Febrile seizures in young children."),
    ("afebrile", "Without fever", "disease", "a-", "febr", "-ile", "a + febr + -ile", "Afebrile 24h often criterion for discharge."),
    ("ambulatory", "Able to walk", "procedure", "", "ambul", "-atory", "ambul (walk) + -atory", "Ambulatory surgery — same-day discharge."),
    ("bedridden", "Confined to bed", "disease", "", "bed", "-ridden", "bed + ridden", "Pressure injury prevention q2h turning."),
    ("palliative", "Relieving without curing", "procedure", "", "palli", "-ative", "palli (cover) + -ative", "Comfort-focused end-of-life care."),
    ("hospice", "End-of-life supportive care", "procedure", "", "hospic", "-e", "hospic + -e", "Six-month prognosis eligibility criterion."),
    ("rehabilitation", "Restoration of function", "procedure", "re-", "habil", "-itation", "re + habil + -itation", "PT/OT/ST interdisciplinary approach."),
    ("prophylaxis", "Disease prevention", "procedure", "", "prophylax", "-is", "prophylax + -is", "DVT prophylaxis for surgical patients."),
    ("immunization", "Process of becoming immune", "procedure", "", "immun", "-ization", "immun + -ization", "CDC schedule guides vaccination timing."),
    ("vaccination", "Introduction of vaccine", "procedure", "", "vaccin", "-ation", "vaccin + -ation", "Document lot number and site."),
    ("quarantine", "Isolation to prevent disease spread", "procedure", "", "quarant", "-ine", "quarant (forty) + -ine", "Infection control during outbreaks."),
    ("isolation", "Separation to prevent transmission", "procedure", "", "isol", "-ation", "isol + -ation", "Standard + transmission-based precautions."),
    ("sterile", "Free from microorganisms", "procedure", "", "steril", "-e", "steril + -e", "Sterile field — 1-inch border rule."),
    ("aseptic", "Free from pathogenic organisms", "procedure", "a-", "sept", "-ic", "a + sept + -ic", "Medical asepsis vs surgical asepsis."),
    ("antiseptic", "Against sepsis/infection", "pharmacology", "anti-", "sept", "-ic", "anti + sept + -ic", "Chlorhexidine skin prep before IV insertion."),
    ("disinfectant", "Chemical that destroys pathogens", "pharmacology", "dis-", "infect", "-ant", "dis + infect + -ant", "Bleach for C. diff spores on surfaces."),
]

def main():
    terms = []
    seen = set()
    for row in CURATED:
        term = row[0]
        if term.lower() in seen:
            continue
        seen.add(term.lower())
        terms.append({
            "term": term,
            "definition": row[1],
            "category": row[2],
            "prefix": row[3] or None,
            "root": row[4] or None,
            "suffix": row[5] or None,
            "breakdown": row[6],
            "clinical_relevance": row[7],
            "source": SOURCE,
        })

    out = Path(__file__).resolve().parent.parent / "data" / "content" / "terminology_terms.json"
    out.write_text(json.dumps({"terms": terms}, indent=2), encoding="utf-8")
    print(f"Wrote {len(terms)} terms to {out}")

if __name__ == "__main__":
    main()